### ISSUE TITLE
openvidu-js-node Deploy on AWS

### ISSUE THREAD

**Issue by talentedandrew** [OpenVidu/openvidu-tutorials#1]
Hi,

Could you provide the documentation for this.

**Comment by micaelgallego** [comment]
Please use the mailing list for questions like this.

In this documentation page you can find information about how to deploy your own nodejs version in the OpenVidu server deployed on AWS

**Comment by micaelgallego** [comment]
Ups... I forgot to include the link. It is:

https://github.com/OpenVidu/openvidu.io-docs/blob/master/docs/deployment/deploying-aws.md

**Comment by talentedandrew** [comment]
thanks a lot and next time I will use mailing list for these types of questions.
