### ISSUE TITLE
Unable to view remote participants video when connected to Wifi

### ISSUE THREAD

**Issue by sravan41-elorce** [OpenVidu/openvidu-tutorials#101]
Working with OpenVidu, We have Integrated OpenVidu in our android application (JAVA). We are facing issue with participants video when connected to a session with WIFI ..We have tried 12 different networks but we could't see participants video streaming in any of the networks. Can you please help us with that.This problem happened with some Mobile Networks as well.

Thanks & Regards
Sravan V

**Comment by micaelgallego** [comment]
Please describe how you have deployed OpenVidu, which version. Can you share OpenVidu logs?

**Comment by sinhaDroid** [comment]
Hi,

We are integrating openvidu with our android application. A month ago, I have deployed development docker image in my aws and tested demo application, it was working fine.
That time KMS version 2.13.0

We starting developing our application and build a layer on top of it. The remote participant is able to join but the video was not rendering. I tried with openvidu demo app, in that also same thing is happening. The video is just blank.

After that, I have update KMS version 2.14.0 also updated openvidu tutorial android app. Then also the same issue. Remote participant video is just blank.

Please help me with the debugging part or check with the latest development whether it's working for you guys.

**Comment by CSantosM** [comment]
That’s really weird.

Two days ago we tested openvidu-android tutorial pointing to demos.openvidu.io and we were able to connect and see others participants  successfully. 

 Could you test thia tutorial pointing to demos.openvidu.io with MY_SECRET as a secret and check if the behavior is exactly the same?

If it is, could you tell us the way to reproduce it step by step?

**Comment by sinhaDroid** [comment]
Thanks for sharing the demo server URL. It worked!

Then, I guess the problem is with the server-side, not an android side. Maybe something broke while updating to KMS version 2.14.0. Let me debug the issue.

Thanks for the help!

**Comment by CSantosM** [comment]
Please, take into account that demos.openvidu.io is only for demos proposes. It’s insecure and publicly accessible by all.

**Comment by athasamid** [comment]
HI, we are facing issue with participant video too, Remote video cannot get video and audio, We already test openvidu-android tutorial pointing to demos.openvidu.io but still can get remote video/audio. 
Thanks

**Comment by micaelgallego** [comment]
Please clone the openvidu-tutorials repository with the new instructions to use the branch "v2.17.0".
