### ISSUE TITLE
Openvidu android: Unable to join using token generated by backend server using Rest apis.

### ISSUE THREAD

**Issue by iit2011081** [OpenVidu/openvidu-tutorials#103]
I have created an api which returns me sessionId and Token. I am using node client for generating token.
So instead of calling getToken() function in android I directly call getTokenSuccess() with sessionId and token which I receive from server. But it is giving error like
```
{
	"id": 0,
	"error": {
		"code": 202,
		"message": "Unable to join session. Session wss:\/\/mycustomdomain.com?sessionId=ses_NmVsb1M9zp&token=tok_CNAPOyx0hveOxD7U&role=PUBLISHER&version=2.14.0&coturnIp=myserver-ip&turnUsername=XBIP27&turnCredential=dfny77 cannot be found. Code: 202"
	},
	"jsonrpc": "2.0"
} 
```

**Comment by pabloFuente** [comment]
There's something wrong in your logic. You are trying to use the token string as the sessionId somehow. The error log is pretty clear:

> Unable to join session. Session ***wss:\/\/mycustom...edential=dfny77*** cannot be found. Code: 202

The bold string is clearly a token, and you are trying to use it as a sessionId.

**Comment by iit2011081** [comment]
I know it is a token when I am passing same token in web(using openvidu js) it is working. I use session.connect(token, { clientData: nickName }) in web and it works as expected. But when I use same using android sdk by calling getTokenSuccess(sessionId, token) it is not working. I want to know why in js, session connect doesn't need sessionId but android sdk needs both sessionId and token.

**Comment by pabloFuente** [comment]
Android SDK is not an SDK. The openvidu-android tutorial directly implements the RPC protocol just as openvidu-browser library (that is, the browser SDK).
To join a session using OpenVidu Server RPC protocol this method must be called through websocket session: https://docs.openvidu.io/en/2.14.0/developing/rpc/#joinroom
This is done in the android tutorial right here: https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-android/app/src/main/java/io/openvidu/openvidu_android/websocket/CustomWebSocket.java#L169

So, parameter "token" should have the string you tried to pass as sessionId. And sessionId should be the actual sessionId.
