### ISSUE TITLE
iOS : Local streams are visible on OPENVIDU WEB(other Participant) end But Remote Streams are coming NIL on my end locally swift iOS

### ISSUE THREAD

**Issue by bhardwajpankaj** [OpenVidu/openvidu-tutorials#105]
I am able to make it working where my Local video can be seen on OpenVidu Web but other person who has joined session from Web whose video(Video Stream and Audio Stream) is not coming at my end. however I can see Remote Participant ID and Name at my end when a user joined the session.

**I have Participant ID what is the way to get Audio Video streams, Do I need to make some connection(Peer connection)? or I will get these streams in the socket connection response only.**

**Comment by micaelgallego** [comment]
![image](https://user-images.githubusercontent.com/1072424/82807825-d97fe580-9e88-11ea-87da-dcd0df8002db.png)
