### ISSUE TITLE
Transparent when multilayer video call

### ISSUE THREAD

**Issue by rizkyalfauji11** [OpenVidu/openvidu-tutorials#109]
![Screenshot (Jun 3, 2020 2_49_10 PM)](https://user-images.githubusercontent.com/46182095/83610485-b1d7fe00-a5a9-11ea-9d0b-0c5f680433cc.png)
<img width="360" alt="Screen Shot 2020-06-03 at 14 52 44" src="https://user-images.githubusercontent.com/46182095/83610626-f2d01280-a5a9-11ea-89ce-2f61177bed96.png">

I am building app one-to-one video call, like other video call apps, but when 2 devices connected, the local participant view becomes transparent. My coding is like the openvidu sample. Please tell me how to resolve my bug.

**Comment by pabloFuente** [comment]
This is not a bug. To get support use the public forum: https://openvidu.discourse.group
