### ISSUE TITLE
Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by stavros-zavrakas** [OpenVidu/openvidu-tutorials#11]
I am trying to follow the hello world tutorial but I have a cors issue and I am not able to find something in the tutorial about that. This is the tutorial that I am following: https://openvidu.io/docs/tutorials/openvidu-hello-world/

I am able to access the openvidu server (https://localhost:4443) login with my secret and test the connection.

I was able to start the openvidu server successfully I am able to fire the POST /api/sessions request and I can see that the response is generated on the openvidu server:
```
2018-05-30 11:11:24,265 DEBG 'kms' stdout output:
0:20:04.507731532     8 0x7f57b0001830 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:422:processMessage: Message: {"id":138,"method":"ping","jsonrpc":"2.0","params":{"sessionId":"1c211ea2-d4b0-4a0c-bf8f-bd543d5792fe"}}
0:20:04.507828568     8 0x7f57b0001830 INFO    KurentoServerMethods ServerMethods.cpp:795:ping: WebSocket Ping/Pong with sessionId 1c211ea2-d4b0-4a0c-bf8f-bd543d5792fe
0:20:04.507923951     8 0x7f57b0001830 DEBUG   KurentoWebSocketTransport WebSocketTransport.cpp:424:processMessage: Response: {"id":138,"jsonrpc":"2.0","result":{"sessionId":"1c211ea2-d4b0-4a0c-bf8f-bd543d5792fe","value":"pong"}}
```

The problem is that the browser rejects the request because of cors issue:
```
- POST https://localhost:4443/api/sessions 401 ()
- (index):1 Failed to load https://localhost:4443/api/sessions: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 401.
```
Is there a place to configure the different acceptable origins?

This is how I start the openvidu server:
`docker run -p 4443:4443 --rm -e openvidu.secret=secret openvidu/openvidu-server-kms`

**Comment by stavros-zavrakas** [comment]
It's not valid anymore. I've realised that I had to visit this url to accept the certificate `https://localhost:4443/accept-certificate` and then update all the references of the `OPENVIDUAPP:MY_SECRET` in the `app.js` with the secret that I've used to start the open-vidu-server-kms.

**Comment by pabloFuente** [comment]
Of course, if you change openvidu-server secret, you will have to modify the hardcoded secret in the client-side code of all insecure (client-side only) tutorials (that includes [openvidu-hello-world](https://openvidu.io/docs/tutorials/openvidu-hello-world/), [openvidu-insecure-js](https://openvidu.io/docs/tutorials/openvidu-insecure-js/), [openvidu-insecure-angular](https://openvidu.io/docs/tutorials/openvidu-insecure-angular/) and [openvidu-getaroom](https://openvidu.io/docs/tutorials/openvidu-getaroom/))

All of them are prepared to show an alert informing about the self-signed certificate of openvidu-server if you try to connect to a session and it is not accepted. If you click OK in the alert, you will be redirected to accept openvidu-server certificate automatically.

**Comment by shashankjamdade** [comment]
After hitting on https://localhost:4443/accept-certificate I get **sessionId 9c8c7bd6-042b-4395-8063-a56a0W9c219L** , Is this secret key you talking about??
