### ISSUE TITLE
Call `leaveSession()` twice will make an ANR in android

### ISSUE THREAD

**Issue by dannyZhou** [OpenVidu/openvidu-tutorials#115]
https://github.com/OpenVidu/openvidu-tutorials/blob/93357b263b799c7e0ac0a262c927187dad12e6b6/openvidu-android/app/src/main/java/io/openvidu/openvidu_android/openvidu/Session.java#L197

Call `leaveSession()` twice will make an ANR in android.

Caused by `peerConnection.close();` call twice will make ANR.

See: https://bugs.chromium.org/p/webrtc/issues/detail?id=6924

Try fix:
https://github.com/OpenVidu/openvidu-tutorials/blob/93357b263b799c7e0ac0a262c927187dad12e6b6/openvidu-android/app/src/main/java/io/openvidu/openvidu_android/openvidu/Session.java#L210

Add `remoteParticipants.clear()` before this line.

https://github.com/OpenVidu/openvidu-tutorials/blob/93357b263b799c7e0ac0a262c927187dad12e6b6/openvidu-android/app/src/main/java/io/openvidu/openvidu_android/openvidu/Participant.java#L87

After this, add `this.peerConnection = null;` 

May be fix this bug.

Sorry my English is poor.

**Comment by Ayman99Shaaban** [comment]
in SessionActivity.java
edit leaveSession by using try/catch
    public void leaveSession() {
        try {
            this.session.leaveSession();
            this.httpClient.dispose();
            viewToDisconnectedState();
        } catch (Exception ignore) {
        }
    }

and best wishes,
[can you help me here please](https://openvidu.discourse.group/t/i-need-to-make-one-to-many-android-java/1985)

**Comment by CSantosM** [comment]
This issue has been fixed on commit a3ee7df193b992bd617a05bca6449ddef7d3cf0c
