### ISSUE TITLE
How openvidu-server-kms and openvidu-insecure-js running distributed servers properly?

### ISSUE THREAD

**Issue by kingkasuo** [OpenVidu/openvidu-tutorials#12]
I deploy openvidu-server-kms in remote server and I deploy tutorial openvidu-insecure-js in my local computer, the result is that I can just access local web page, but can not see any streaming video properly.  Is there anything shoud I modify?

**Comment by pabloFuente** [comment]
Docker setup (image `openvidu-server-kms`) is not supported in deployment environments
