### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by pankajnegi1893** [OpenVidu/openvidu-tutorials#120]
While Connecting with OpenVidu in React Native. We are getting error java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. while connecting with wss Url in WebSocketWithReconnection.js class in Release APK. But in debug mode  it's working fine.

**Comment by CSantosM** [comment]
Please, try with our development environment to check if the problem is in your side or in ours.

url: https://demos.openvidu.io/
secret: MY_SECRET

**Comment by pankajnegi1893** [comment]
But in your demo react native project I am not able to find openvidu-react-native-adapter library. So I am unable to test.

**Comment by CSantosM** [comment]
![image](https://user-images.githubusercontent.com/10628395/88895725-272e1b00-d249-11ea-8bc7-cc088c452fcc.png)
