### ISSUE TITLE
Ask about ip camera video 

### ISSUE THREAD

**Issue by cheesecat47** [OpenVidu/openvidu-tutorials#121]
Hello, I want to make a video call app using OpenVidu.
So I'm studying with openvidu-ionic example.
What I'm asking about is, can I connect the ip camera video as if it is a user's video?
There was rest api in ip camera example in the document, but I can't understand well how to use it exactly.
I wonder if it is possible in ionic.
Thank you.

**Comment by micaelgallego** [comment]
Yes, you can add an IPCamera to a session like any other user. Take a look to the docs.

Please use the public forum https://openvidu.discourse.group for technical questions.

Regards
