### ISSUE TITLE
Certification Error

### ISSUE THREAD

**Issue by paramony** [OpenVidu/openvidu-tutorials#122]
I run OpenVidu Server On Public IP 192.168.1.70:4443 but in google Chrome Get Me this Error net::ERR_CERT_AUTHORITY_INVALID but in firefox everything is ok . how to fix this error completeley ?

**Comment by volkankoc** [comment]
chrome address line
Connect to **192.168.1.70:4443/** and accept the insecure certificate
or 
Connect to **https://localhost:4443/** and accept the insecure certificate

**Comment by micaelgallego** [comment]
To avoid certificate errors you will need a valid domain to create a valid certificate.
