### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by paramony** [OpenVidu/openvidu-tutorials#123]
How To Deploy OpenVidu Server On Windows Server Please Tell Me Step By Step . Documentation in OpenVidu Website Not So Good For This Item

**Comment by pabloFuente** [comment]
![Screenshot_20200809-121823](https://user-images.githubusercontent.com/15049534/89729952-96222580-da3a-11ea-866d-9d02dd23e48a.jpg)

**Comment by paramony** [comment]
openvidu not deploy on windows server ?
