### ISSUE TITLE
openvidu-insecure-react tutorial npm install fails

### ISSUE THREAD

**Issue by banagale** [OpenVidu/openvidu-tutorials#127]
Dependency error related to jest-haste-map and fsevents.

`fsevents@1.2.13 install /code/learning/openvidu/openvidu-tutorials/openvidu-insecure-react/node_modules/jest-haste-map/node_modules/fsevents`

Is resolved by using updated react packages in package.json as per below and re-running `npm install`.

```
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-scripts": "^3.4.3"
```

**Comment by banagale** [comment]
Seems you have a workflow for updating this across all of the tutorials using `update-tutorials.sh`. Feel free to close or let me know if a PR to fix just this tutorial would be helpful.

**Comment by CSantosM** [comment]
Thanks, 
yes please, create a PR and we'll include it.
