### ISSUE TITLE
openvidu not working in iPhone and iPad safari

### ISSUE THREAD

**Issue by hollomyfoolish** [OpenVidu/openvidu-tutorials#13]
Hi,
I set up an openvidu-mvc-node environment with version 2.4.0, it works well bonth in PC chrome and Mac chrome, but saddly it doesn't work in iPhone safari and iPad safari. Actually I debugged the codes in iPad safari and I found out the below variable mediaStream is undefined (in file openvidu-browser-2.4.0.js line number 5150), and I can get a successfuly mediaStream in PC chome, it seems that we can't get remote stream from peerConnection in iPad safari.

    Stream.prototype.remotePeerSuccessfullyEstablished = function () {
        **this.mediaStream = this.webRtcPeer.pc.getRemoteStreams()[0];**
        console.debug('Peer remote stream', this.mediaStream);
        if (!!this.mediaStream) {
            this.ee.emitEvent('mediastream-updated');
            if (!this.displayMyRemote() && !!this.mediaStream.getAudioTracks()[0] && this.session.speakingEventsEnabled) {
                this.enableSpeakingEvents();
            }
        }
    };

I also tried another demo following this tutorils: https://apple.openvidu.io/ , this demo works fine both in iPad and iPhone safari, do you know anything different between the tow demos? Is there any specail configuration  I need to know? Advanced thanks for your help.

**Comment by mname** [comment]
I have the same problem. I tried to use openvidu-tutorials/openvidu-hello-world.

**Comment by pabloFuente** [comment]
OpenVidu works now fine in Safari with release 2.7.0

**Comment by loveisalie92** [comment]
I have upgraded to use openvidu-browser-2.7.0.js but still can't get safari on phone, ipad to publish streams.
Works fine on android devices.
Is there any steps that i am missing? Appreciate your help

**Comment by micaelgallego** [comment]
Have you tested official tutorials?

**Comment by monavie1989** [comment]
Have some body fixed this problem.
I have problem too

**Comment by CSantosM** [comment]
I have tested  [openvidu-ionic](https://openvidu.io/docs/tutorials/openvidu-ionic/) app and [openvidu-insecure-js](https://openvidu.io/docs/tutorials/openvidu-insecure-js/) all of them with **openvidu-browser2.10.0** in **iPhone7** and **iPhone7 Plus** and they are working fine.
Please follow the official tutorials.

**Comment by monavie1989** [comment]
> I have tested [openvidu-ionic](https://openvidu.io/docs/tutorials/openvidu-ionic/) app and [openvidu-insecure-js](https://openvidu.io/docs/tutorials/openvidu-insecure-js/) all of them with **openvidu-browser2.10.0** in **iPhone7** and **iPhone7 Plus** and they are working fine.
> Please follow the official tutorials.

Thanks your reply
I Deploying OpenVidu on Ubuntu (EC2 on aws.amazon.com, Ubuntu Bionic 18.04)
and I sure already follow your official tutorials
https://openvidu.io/docs/deployment/deploying-ubuntu/

this is my app demo url
https://site4company.com/openvidu-insecure-js/web/
it working well on PC browser, but in my Iphone6s plus when I click join button nothing to do
can you help me take a a look my app.
thanks you so much
