### ISSUE TITLE
deploy vue application

### ISSUE THREAD

**Issue by chinarui-na** [OpenVidu/openvidu-tutorials#130]
i want to deploy application write by vue .
i run npm run build.
i want deploy it to linux machion with openvidu-server in.
how to do it.
by the way.i want visit it with https://domain

**Comment by pabloFuente** [comment]
What kind of issue is this? If this is a support question, write it on the public forum: https://openvidu.discourse.group/
To deploy OpenVidu: https://docs.openvidu.io/en/latest/deployment/
To deploy a Vue app: https://vuejs.org/v2/guide/deployment.html
