### ISSUE TITLE
How to enable/disable video on Android native

### ISSUE THREAD

**Issue by rahadzaman** [OpenVidu/openvidu-tutorials#132]

**Comment by Widiyanto** [comment]
`public void enableLocalVideo(boolean a){
        videoTrack.setEnabled(a);
    }

    public void enableLocalAudio(boolean a){
        audioTrack.setEnabled(a);
    }`

**Comment by CSantosM** [comment]
Use [OpenVidu Forum](https://openvidu.discourse.group/) for questions instead issue tracker please
