### ISSUE TITLE
video not showing error when other subscriber/participant leaves

### ISSUE THREAD

**Issue by scl2589** [OpenVidu/openvidu-tutorials#138]
We are currently utilizing openvidu-insecure-vue to create our service and we have found the following error.

When there's multiple subscribers and a subscriber leaves the room, sometimes other participants' videos disappears.

![image](https://user-images.githubusercontent.com/25967949/99332236-7fa22a80-28c3-11eb-9487-a9e8d49259e4.png)
![image](https://user-images.githubusercontent.com/25967949/99332319-8630a200-28c3-11eb-955e-fef3da52af20.png)

Please refer to the image above. 
In the image, even though the **Participant15** remains in the room, the video of the **Participant15** has disappeared. This happened after **Participant65** has left the room.

I believe the problems occurs from setting the key with index.
The following code is referred from openvidu-insecure-vue/src/App.vue (31st ~ 34th line)
```
<div id="video-container" class="col-md-6">
            <user-video :stream-manager="publisher" @click.native="updateMainVideoStreamManager(publisher)"/>
            <user-video v-for="(sub, index) in subscribers" :key="index" :stream-manager="sub" @click.native="updateMainVideoStreamManager(sub)"/>
         </div>
```
It can be solved by changing the index to the unique id.

**Comment by pabloFuente** [comment]
Fix merged. Thank you!
