### ISSUE TITLE
Running without Docker container

### ISSUE THREAD

**Issue by AlexPrietoBlanco** [OpenVidu/openvidu-tutorials#14]
Hello,

I would like to know if it is possible to run this demo without running the docker container.

Thank you in advance.
Alex.

**Comment by pabloFuente** [comment]
You can run the Docker container or you can install OpenVidu Server in an Ubuntu machine (see Deployment section in OpenVidu Docs: https://openvidu.io/docs/home/)

**Comment by AlexPrietoBlanco** [comment]
I have a OpenVidu Server running in my Ubuntu machine but I don't know how to run the getaroom demo properly.

**Comment by micaelgallego** [comment]
What problem do you have exactly?

**Comment by AlexPrietoBlanco** [comment]
I want to run this demo without using Docker but I don't know how to do that. I have cloned the repo from git and I have A OpenVidu Server (from the Deployment section in OpenVidu Docs: https://openvidu.io/docs/home/) running on my PC.

**Comment by micaelgallego** [comment]
Follow the instructions https://openvidu.io/docs/demos/openvidu-getaroom/

**Comment by AlexPrietoBlanco** [comment]
I have already done that, but the 4th instructuion uses Docker and I wanted to try running that without Docker.

**Comment by micaelgallego** [comment]
Aa you have KMS and OpenVidu server installed locally, simply ignore this instruction
