### ISSUE TITLE
Android client receive 2 connections for every remote participant.

### ISSUE THREAD

**Issue by jaswant0605** [OpenVidu/openvidu-tutorials#143]
I've been working with the android client and found out that the websocket event for new participant joined triggers twice for every new participant joining. 
Both has different connection IDs
If the first remote connection clientData is "jaswant" the second is "jaswant_SCREEN".

Does anyone know how to resolve this?

**Comment by CSantosM** [comment]
Hi @jaswant0605 ,

Im pretty sure that you are using the OpenVidu Call for your tests. If you use another demo like [basic webinar](https://demos.openvidu.io/basic-videoconference/) you won't see this behaviour. 

This is not a bug with openvidu-android tutorial, it is simply OpenVidu Call app behaviour
