### ISSUE TITLE
 Attempted to assign to readonly property - React native

### ISSUE THREAD

**Issue by mayander30** [OpenVidu/openvidu-tutorials#144]
When I try use the package shared with me show this message

const ovReact = new OpenViduReactNativeAdapter();
ovReact.initialize();

TypeError: Attempted to assign to readonly property.

The error show when will initialize “ovReact.initialize();”.

I tried with example in site, when execute show this error… I think is the package that I bought.

Iam using openvidu-react-native-adapter-2.16.0.tgz

package:
"dependencies": {
    "@emotion/core": "^10.0.28",
    "@emotion/native": "^10.0.27",
    "@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/datetimepicker": "2.4.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/picker": "1.6.0",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/material-top-tabs": "^5.1.1",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "axios": "^0.19.2",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint-import-resolver-webpack": "^0.12.1",
    "humps": "^2.0.1",
    "i18next": "^15.1.3",
    "i18next-xhr-backend": "^2.0.1",
    "libphonenumber-js": "^1.9.6",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "openvidu-react-native-adapter": "./openvidu-react-native-adapter-2.16.0.tgz",
    "prop-types": "^15.7.2",
    "ramda": "^0.27.0",
    "react": "16.13.1",
    "react-dom": "16.11.0",
    "react-hook-form": "^6.3.2",
    "react-i18next": "^11.8.4",
    "react-native": "0.62.2",
    "react-native-animatable": "^1.3.3",
    "react-native-autocomplete-tags": "^2.0.0",
    "react-native-camera": "^3.40.0",
    "react-native-collapsible": "^1.5.3",
    "react-native-device-info": "^7.3.1",
    "react-native-flash-message": "^0.1.16",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-image-picker": "^3.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-localize": "^2.0.1",
    "react-native-masked-text": "^1.13.0",
    "react-native-material-menu": "^1.2.0",
    "react-native-modal": "^11.5.6",
    "react-native-modal-datetime-picker": "^8.9.3",
    "react-native-phone-number-input": "^2.0.0",
    "react-native-reanimated": "~1.9.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0",
    "react-native-skeleton-content": "^1.0.13",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "12.1.0",
    "react-native-tab-view": "^2.14.4",
    "react-native-unimodules": "~0.10.1",
    "react-native-vector-icons": "^7.0.0",
    "react-native-web": "~0.11.7",
    "react-navigation-material-bottom-tabs": "^2.3.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "reduxsauce": "^1.1.2",
    "reselect": "^4.0.0",
    "seamless-immutable": "^7.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^2.5.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "16.13.1",
    "prettier": "^1.19.1",
    "prettier-eslint": "^9.0.1"
  },

**Comment by CSantosM** [comment]
Hello @mayander30 ,

This bug is fixed in the 2.16.1 version.
If you don’t have this library, please send an email to our commercial mail commercial@openvidu.io.

Regards
