### ISSUE TITLE
Crash when release mode with  minifyEnabled true

### ISSUE THREAD

**Issue by james04gr** [OpenVidu/openvidu-tutorials#146]
I think that you have to provide a proguard guide because when i create a release mode i cannot open the Activity!

**Comment by micaelgallego** [comment]
This repository contains several applications. Can you be more precise about the specific tutorial with the issue? 

Also, can you detail with detailed steps and commands what is the expected behavior and the current one?

Regards

**Comment by CSantosM** [comment]
Closed for inactivity.
