### ISSUE TITLE
Commit ee7994c149d5a44c1ff65daf5c634777a9d139ee is broken on android

### ISSUE THREAD

**Issue by jaswant0605** [OpenVidu/openvidu-tutorials#150]
The commit ee7994c149d5a44c1ff65daf5c634777a9d139ee is not working, Remote user's video is not visible. onAddTrack is never called. 
Use the commit from 13 Nov instead (Commit a24ecac4e478578ff94e5ac786eae3547285fc22), its working even on the latest instance (2.17.0 as of now).

**Comment by pabloFuente** [comment]
You are right. This commit is supposed to work with master version of OpenVidu Server. So the tutorial instructions (which directly clone master of openvidu-tutorials repository) are actually broken right now for the openvidu-android tutorial.

`git checkout 0752d4edcccc979d8c62b9b9fe4b86f70d6d7568` on openvidu-tutorials repository should avoid the problem.
We will "checkout" commands to tutorials instructions to avoid this issue in the future.

**Comment by vjvk** [comment]
Hi,
Please suggest me to checkout the exact tutorial for an android, as I am unable to load remote participant's video.
Also I tried this `git checkout 0752d4edcccc979d8c62b9b9fe4b86f70d6d7568` commit, still I am facing this issue.
Web and iOS has no issues on connecting the videos. But in Android we facing an issue for past two days, unable to resolve.
Kindly help us to figure out this as soon as possible, we are in urgent to release.
