### ISSUE TITLE
Browser Yandex Browser is not supported in OpenVidu

### ISSUE THREAD

**Issue by AlexCollin** [OpenVidu/openvidu-tutorials#154]
Hello! I using demo OpenVidu call 
On Yandex browser i get error:

There was an error connecting to the session:
Browser Yandex Browser (version 21.5.0.625) for OS X is not supported in OpenVidu

MacOS 11.2.3 (20D91)
Mac mini (2018)

**Comment by pabloFuente** [comment]
Hi.
Whay do you not understand about this error? I think it is pretty self explanatory, isn't it?
