### ISSUE TITLE
openvidu-hello-world

### ISSUE THREAD

**Issue by yunhai2009** [OpenVidu/openvidu-tutorials#16]
hi
others can internet this web，but can not join . 
i can internet this web ande join.
why?
thank you.

**Comment by micaelgallego** [comment]
Can you explain what is your problem?

**Comment by yunhai2009** [comment]
hi @micaelgallego 
I build a web server with VMware ，and run ”openvidu-hello-world”. i can join by clicking the join button, others can visit website but can not join by clicking the join button. status is 200 ok.

**Comment by micaelgallego** [comment]
You have to follow the steps in the doc:

https://openvidu.io/docs/deployment/deploying-ubuntu/

Be sure that you instance has all relevant ports open and the public IP is properly configured in the services.

**Comment by yunhai2009** [comment]
hi @micaelgallego
I follow the steps in the doc .
My question is that i can click the join button and join but others can not. 
thanks.

**Comment by micaelgallego** [comment]
Please send post here the logs of openvidu-server.jar and the contents of the browser console of all participants.

**Comment by yunhai2009** [comment]
@micaelgallego 

[failed.txt](https://github.com/OpenVidu/openvidu-tutorials/files/2623480/failed.txt)
[successfull.txt](https://github.com/OpenVidu/openvidu-tutorials/files/2623481/successfull.txt)

**Comment by yunhai2009** [comment]
> Please send post here the logs of openvidu-server.jar and the contents of the browser console of all participants.

@micaelgallego hi I found out the reason for the error

docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://192.168.99.100:4443/ openvidu/openvidu-server-kms:2.6.0

openvidu.publicurl was setted wrong。

thank you.
