### ISSUE TITLE
Customizing OpenVidu Web Component

### ISSUE THREAD

**Issue by shazimKhan** [OpenVidu/openvidu-tutorials#160]
Hello,
I am looking for to customize openvidu-webcomponent as per my need. I don't see it that much dynamic when it comes customizing it through apps. 
Where can I find the source code of webcomponent and how to compile it down???
Your help would be really appreciated

**Comment by pabloFuente** [comment]
https://docs.openvidu.io/en/latest/developing/#compiling-openvidu-webcomponent
