### ISSUE TITLE
Changing Call Window styling

### ISSUE THREAD

**Issue by richard-dch** [OpenVidu/openvidu-tutorials#162]
I have recently created an Angular application with OpenVidu installed and configured.

I was wondering if there is a possibility of customising the call window, and if so to what degree and limitations this can be done. 

I am calling the hidden component `OpenviduSessionComponent` my openvidu typescript file:
```
@ViewChild('ovSessionComponent')
	public ovSessionComponent: OpenviduSessionComponent;
```
Many of the functions coming from this component are being used also, so I dont want to change the component I am using, just want to change its look i.e styling.

So far I have only been able to change this component by inspecting it using developer tools and then calling the hidden classes inside my openvidu css file and changing its properties. I have not found any html or css behind the ovSessionComponent component, or its sub-components either

Thank You.

<img width="1308" alt="Screenshot 2021-07-29 at 11 05 54" src="https://user-images.githubusercontent.com/70823153/127473451-88a08474-20fc-41a6-b55b-802ee0676d50.png">

**Comment by CSantosM** [comment]
You can change everything you want in OpenVidu Call repository. Check this link https://docs.openvidu.io/en/2.19.0/developing/

By the way, use the public forum for question. This is only for bugs.
