### ISSUE TITLE
/openvidu-node-client/lib/Session.js:473:28   NO RESPONSE AT ALL

### ISSUE THREAD

**Issue by zlatnaspirala** [OpenVidu/openvidu-tutorials#169]
I use docker 

My test case on 4443 works fine!

Error log on server (node app) -> (NO RESPONSE AT ALL)

New session ccffff
Error: [object Object]
    at /var/applications/kure/kure-server-client/node_modules/openvidu-node-client/lib/Session.js:473:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Event: onClose
Getting a token | {sessionName}={ccffff}
New session ccffff
Error: [object Object]
    at /var/applications/kure/kure-server-client/node_modules/openvidu-node-client/lib/Session.js:473:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
This is from chrome :

Request URL: https://maximumroulette.com:2020/api/get-token
Referrer Policy: strict-origin-when-cross-origin
:authority: maximumroulette.com:2020
:method: POST
:path: /api/get-token
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,ru;q=0.8
cache-control: no-cache
content-length: 34
content-type: application/json
cookie: JSESSIONID=6B447357184889E15A9D1EEFF2E49891
origin: https://maximumroulette.com:2020
pragma: no-cache
referer: https://maximumroulette.com:2020/
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

I change also 

        "//secure": {
            "//port": 8433,
            "//certificate": "defaultCertificate.pem",
            "//password": ""
        },

to 

   "secure": {
            "port": 8433,
            "certificate": "defaultCertificate.pem",
            "password": "my PASS FROM CREATING key cert"
        },

ANY SUGGESTION !

**Comment by micaelgallego** [comment]
Can you describe how have you deployed OpenVidu and what is the operation you are executing giving the error?

If your test is working with 4443, why are you changing it?

**Comment by zlatnaspirala** [comment]
Thnks for time!
 
 To make more clear i will use for node standard 443 port.  I also wanna migrate to 2.20.0 version.
 I created cert from my letsencrypt cert for my domain maximumroulette.com.

 I see different way for docker args [2.20.0].
**Is this still works :** 
```-e  server.ssl.key-store -e server.ssl.key-store-password=***** -e server.ssl.key-alias=YOUR_KEYSTORE_ALIAS```
??

I already inject JKS file intro container and remake docker image [maxi-2:2.20.0].


Now i dont have access at  https://maximumroulette.com:4443

```
docker run -d -p 4443:4443 -e OPENVIDU_SECRET=MAXIMUM -e HTTPS_PORT=443 -e DOMAIN_OR_PUBLIC_IP=https://maximumroulette.com -e OPENVIDU_CDR=true -e OPENVIDU_RECORDING=false -e OPENVIDU_RECORDING_PATH=/var/applications/kurento-project/rec -e OPENVIDU_RECORDING_PUBLIC_ACCESS=true -e server.ssl.key-store=/var/applications/kurento-project/KURE.jks -e server.ssl.key-store-password=***** -e server.ssl.key-alias=YOUR_KEYSTORE_ALIAS maxi-2:2.20.0
```

**Comment by micaelgallego** [comment]
We do not support using the development container for production usage (with a domain).

So please follow these instructions to deploy OpenVidu CE in a productive environment https://docs.openvidu.io/en/stable/deployment/ce/on-premises/ 

If you have any issue with deployment please use the public forum https://openvidu.discourse.group.

Regards
