### ISSUE TITLE
openvidu-js-node is not working

### ISSUE THREAD

**Issue by keisen** [OpenVidu/openvidu-tutorials#17]
Hi OpenVidu team, Thank you for your great work!

Now I'm trying the tutorial[ `openvidu-js-node` ] but it's not working.
It's able to logged in, but not able to `join` .

The following is occuring error on `server.js` .

```
vagrant@vagrant-ubuntu-trusty-64:~/workspace/openvidu-tutorials/openvidu-js-node$ node server.js localhost:4443 MY_SECRET
App listening on port 5000
Logging in | {user, pass}={publisher1, pass}
'publisher1' has logged in
Getting a token | {sessionName}={Session 7}
New session Session 7
Writable {
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree: CorkedRequest { next: null, entry: null, finish: [Function] } },
  writable: true,
  domain: null,
  _events:
   { response: [Function: handleResponse],
     error: [Function: handleRequestError] },
  _eventsCount: 2,
  _maxListeners: undefined,
  _options:
   { protocol: 'https:',
     maxRedirects: 21,
     maxBodyLength: 10485760,
     path: 'https://localhost:4443/api/sessions',
     method: 'post',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 129,
        host: 'localhost:4443' },
     agent: undefined,
     auth: undefined,
     hostname: '192.168.56.1',
     port: '3128',
     host: '192.168.56.1',
     nativeProtocols: { 'http:': [Object], 'https:': [Object] },
     pathname: 'https://localhost:4443/api/sessions' },
  _redirectCount: 0,
  _redirects: [],
  _requestBodyLength: 129,
  _requestBodyBuffers:
   [ { data: <Buffer 7b 22 6d 65 64 69 61 4d 6f 64 65 22 3a 22 52 4f 55 54 45 44 22 2c 22 72 65 63 6f 72 64 69 6e 67 4d 6f 64 65 22 3a 22 4d 41 4e 55 41 4c 22 2c 22 64 65 ... >,
       encoding: undefined } ],
  _onNativeResponse: [Function],
  _currentRequest:
   ClientRequest {
     domain: null,
     _events:
      { response: [Object],
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedHeader: { 'content-length': false },
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 396,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        _bytesDispatched: 396,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _header: 'POST https://localhost:4443/api/sessions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 129\r\nhost: localhost:4443\r\nConnection: close\r\n\r\n',
     _headers:
      { accept: 'application/json, text/plain, */*',
        'content-type': 'application/json',
        authorization: 'Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU',
        'user-agent': 'axios/0.18.0',
        'content-length': 129,
        host: 'localhost:4443' },
     _headerNames:
      { accept: 'Accept',
        'content-type': 'Content-Type',
        authorization: 'Authorization',
        'user-agent': 'User-Agent',
        'content-length': 'Content-Length',
        host: 'host' },
     _onPendingData: null,
     agent:
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: 'https://localhost:4443/api/sessions',
     _ended: false,
     _redirectable: [Circular],
     parser: null },
  _currentUrl: 'https://192.168.56.1/https://localhost:4443/api/sessions' }
Error: [object Object]
    at /home/vagrant/workspace/openvidu-tutorials/openvidu-js-node/node_modules/openvidu-node-client/lib/Session.js:417:28
```

Please tell me how I should do.
Best regards.

**Comment by pabloFuente** [comment]
Are you following exactly the commands stated here?: https://openvidu.io/docs/tutorials/openvidu-js-node/#running-this-tutorial

You probably have some kind of connection problem between the node app and OpenVidu Server.  You must launch your node server with command `node server.js localhost:4443 MY_SECRET`, changing `localhost:4443` for the proper URL where your OpenVidu Server is listenting (maybe "https://192.168.0.XXX:4443/" or something similar, dependeing on how you launched it)

**Comment by keisen** [comment]
Thank you for your prompt response!

> Are you following exactly the commands stated here?
Yes, I'm.
Of course, I wrote correct command (i.e.,  `MY_SECRET` ), please look above log.

**Comment by keisen** [comment]
Hi @pabloFuente .
I retryed but got not working.

> (maybe "https://192.168.0.XXX:4443/" or something similar, dependeing on how you launched it)

I ran the commands follow as:

```
node server.js 127.0.0.1:4443 MY_SECRET
```
and
```
sudo docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.6.0
```

Then proceeded to run `netstat` for checking ip and port.

```
$ netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:60382           0.0.0.0:*               LISTEN     
tcp        0      0 10.0.2.15:22            10.0.2.2:61659          ESTABLISHED
tcp        0      0 10.0.2.15:5000          10.0.2.2:55894          TIME_WAIT  
tcp6       0      0 :::35175                :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::4443                 :::*                    LISTEN     
udp        0      0 0.0.0.0:961             0.0.0.0:*                          
・・・
```

It seems working well.
Actually, WebBrowser can directly access to the port (i.e., `https://127.0.0.1:4443` ) .

As you said, it will be probably some kind of connection problem between the node app and OpenVidu Server.
So I tryed multiple urls (i.e., `localhost` , `127.0.0.1` , `192.168.0.1-10` , `192.168.56.1-10` and etc) .
But....

I don't know how I should do. 
Do I have any mistake?

**Comment by keisen** [comment]
Resolved!

The cause of this issue is proxy settings.
My development environment is set `https_proxy` (, `http_proxy`) and `no_proxy` as EnvironmentVariables,
but It seems the axios being used openvidu-tutorials don't refer `no_proxy`.
So between the node app and OpenVidu Server could not connect, maybe.

Thank you and best regards.

**Comment by sourabh947** [comment]
Hi OpenVidu team, 
i am also getting same error.

> Are you following exactly the commands stated here?: https://openvidu.io/docs/tutorials/openvidu-js-node/#running-this-tutorial
> 
> You probably have some kind of connection problem between the node app and OpenVidu Server. You must launch your node server with command `node server.js localhost:4443 MY_SECRET`, changing `localhost:4443` for the proper URL where your OpenVidu Server is listenting (maybe "https://192.168.0.XXX:4443/" or something similar, dependeing on how you launched it)

i was tried this also but it's not working

**Comment by micaelgallego** [comment]
Try connecting to https://demos.openvidu.io:4443/ with user: OPENVIDUAPP and pass: MY_SECRET to see if it is working with a tested OpenVidu deployment.

**Comment by sourabh947** [comment]
Thank you ,
It's not working with a tested OpenVidu deployment.
 I run command like this **node server.js https://demos.openvidu.io:4443:4443 MY_SECRET**

**Comment by CSantosM** [comment]
Hello @sourabh947 
I have tested **openvidu-js-node** and it's working correctly.
I ran ```node server.js demos.openvidu.io:4443 MY_SECRET```
Which are your error logs?

**Comment by designerprasan007** [comment]
do you have the same output for all docker commands? I want to get the openvidu-getaroom but unfortunately i'm getting only oneoutput of that testing page

**Comment by designerprasan007** [comment]
> Resolved!
> 
> The cause of this issue is proxy settings.
> My development environment is set `https_proxy` (, `http_proxy`) and `no_proxy` as EnvironmentVariables,
> but It seems the axios being used openvidu-tutorials don't refer `no_proxy` (i.e., the proxy was applied all urls) .
> So between the node app and OpenVidu Server could not connect, maybe.
> 
> Thank you and best regards.

can you tell us please where did you done this all?

**Comment by deepinder10** [comment]
same error, is there any resolution?

**Comment by micaelgallego** [comment]
It seems there is a connection problem between your app and OpenVidu Platform.

Please review you can access to any URL using a curl or other command. https://openvidu.io/docs/reference-docs/REST-API/

**Comment by micaelgallego** [comment]
This error can happen if you use a self signed certificate to deploy OpenVidu platform.

If that is your case, it can be avoided using:
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = “0”;
```
[Thanks](https://openvidu.discourse.group/t/strange-response-from-openvidu-node-client-library/391/5) to Mirko_Bertone

**Comment by ajmc90** [comment]
I have the same issue. I have this line added by default "process.env.NODE_TLS_REJECT_UNAUTHORIZED = “0”;"

**This is my docker-compose.yml file:**

`version: '3'

services:
  kurento:
    image: kurento/kurento-media-server
    network_mode: bridge
    expose:
      - "8888"
    ports:
      - 8888:8888
    volumes:
      - /usr/src/app/broadcast/:/usr/src/app/broadcast/
  openvidu-server-kms:
    container_name: openvidu-server-kms
    image: openvidu/openvidu-server-kms:2.16.0
    network_mode: bridge
    ports:
      - "4443:4443"
    expose:
      - "4443"
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=docker
  node-server:
    build: ./
    network_mode: bridge
    ports:
      - "5000:5000"
    depends_on:
      - openvidu-server-kms
    links:
      - openvidu-server-kms
    tty: true`
    

**This is my Dockerfile**
    
    `FROM node:15.5.0

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install pm2 -g
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 5000

# CMD [ "pm2-runtime" ,"./server.js", "https://localhost:5000", "MY_SECRET" ]
CMD [ "node", "--trace-warnings" ,"./server.js", "https://localhost:4443", "MY_SECRET" ]`

**And this is the error that I'm getting:**

`(node:1) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

at getAllowUnauthorized (node:internal/options:21:13)

at Object.connect (node:_tls_wrap:1581:29)

at Agent.createConnection (node:https:130:22)

at Agent.createSocket (node:_http_agent:323:26)

at Agent.addRequest (node:_http_agent:274:10)

at new ClientRequest (node:_http_client:314:16)

at Object.request (node:https:326:10)

at RedirectableRequest._performRequest (/usr/src/app/node_modules/follow-redirects/index.js:241:24)

at new RedirectableRequest (/usr/src/app/node_modules/follow-redirects/index.js:60:8)

at Object.request (/usr/src/app/node_modules/follow-redirects/index.js:437:14)

<ref *2> Writable {

_writableState: WritableState {

objectMode: false,

highWaterMark: 16384,

finalCalled: false,

needDrain: false,

ending: false,

ended: false,

finished: false,

destroyed: false,

decodeStrings: true,

defaultEncoding: 'utf8',

length: 0,

writing: false,

corked: 0,

sync: true,

bufferProcessing: false,

onwrite: [Function: bound onwrite],

writecb: null,

writelen: 0,

afterWriteTickInfo: null,

buffered: [],

bufferedIndex: 0,

allBuffers: true,

allNoop: true,

pendingcb: 0,

constructed: true,

prefinished: false,

errorEmitted: false,

emitClose: true,

autoDestroy: true,

errored: null,

closed: false,

closeEmitted: false,

[Symbol(kOnFinished)]: []

},

_events: [Object: null prototype] {

response: [Function: handleResponse],

error: [Function: handleRequestError]

},

_eventsCount: 2,

_maxListeners: undefined,

_options: {

maxRedirects: 21,

maxBodyLength: 10485760,

protocol: 'https:',

path: '/openvidu/api/sessions',

method: 'POST',

headers: {

Accept: 'application/json, text/plain, */*',

'Content-Type': 'application/json',

Authorization: 'Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU',

'User-Agent': 'axios/0.21.0',

'Content-Length': 160

},

agent: undefined,

agents: { http: undefined, https: undefined },

auth: undefined,

hostname: 'localhost',

port: '4443',

nativeProtocols: { 'http:': [Object], 'https:': [Object] },

pathname: '/openvidu/api/sessions'

},

_ended: false,

_ending: true,

_redirectCount: 0,

_redirects: [],

_requestBodyLength: 160,

_requestBodyBuffers: [

{

data: <Buffer 7b 22 6d 65 64 69 61 4d 6f 64 65 22 3a 22 52 4f 55 54 45 44 22 2c 22 72 65 63 6f 72 64 69 6e 67 4d 6f 64 65 22 3a 22 4d 41 4e 55 41 4c 22 2c 22 64 65 ... 110 more bytes>,

encoding: undefined

}

],

_onNativeResponse: [Function (anonymous)],

_currentRequest: <ref *1> ClientRequest {

_events: [Object: null prototype] {

response: [Function],

socket: [Function (anonymous)],

abort: [Function (anonymous)],

aborted: [Function (anonymous)],

connect: [Function (anonymous)],

error: [Function (anonymous)],

timeout: [Function (anonymous)]

},

_eventsCount: 7,

_maxListeners: undefined,

outputData: [],

outputSize: 0,

writable: true,

destroyed: false,

_last: true,

chunkedEncoding: false,

shouldKeepAlive: false,

_defaultKeepAlive: true,

useChunkedEncodingByDefault: true,

sendDate: false,

_removedConnection: false,

_removedContLen: false,

_removedTE: false,

_contentLength: null,

_hasBody: true,

_trailer: '',

finished: false,

_headerSent: true,

_closed: false,

socket: TLSSocket {

_tlsOptions: [Object],

_secureEstablished: false,

_securePending: false,

_newSessionPending: false,

_controlReleased: true,

secureConnecting: true,

_SNICallback: null,

servername: null,

alpnProtocol: null,

authorized: false,

authorizationError: null,

encrypted: true,

_events: [Object: null prototype],

_eventsCount: 11,

connecting: false,

_hadError: true,

_parent: null,

_host: 'localhost',

_readableState: [ReadableState],

_maxListeners: undefined,

_writableState: [WritableState],

allowHalfOpen: false,

_sockname: null,

_pendingData: [Array],

_pendingEncoding: '',

server: undefined,

_server: null,

ssl: null,

_requestCert: true,

_rejectUnauthorized: false,

parser: null,

_httpMessage: [Circular *1],

[Symbol(res)]: [TLSWrap],

[Symbol(verified)]: false,

[Symbol(pendingSession)]: null,

[Symbol(async_id_symbol)]: 446,

[Symbol(kHandle)]: null,

[Symbol(kSetNoDelay)]: false,

[Symbol(lastWriteQueueSize)]: 0,

[Symbol(timeout)]: null,

[Symbol(kBuffer)]: null,

[Symbol(kBufferCb)]: null,

[Symbol(kBufferGen)]: null,

[Symbol(kCapture)]: false,

[Symbol(kBytesRead)]: 0,

[Symbol(kBytesWritten)]: 0,

[Symbol(connect-options)]: [Object]

},

_header: 'POST /openvidu/api/sessions HTTP/1.1\r\n' +

'Accept: application/json, text/plain, */*\r\n' +

'Content-Type: application/json\r\n' +

'Authorization: Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU\r\n' +

'User-Agent: axios/0.21.0\r\n' +

'Content-Length: 160\r\n' +

'Host: localhost:4443\r\n' +

'Connection: close\r\n' +

'\r\n',

_keepAliveTimeout: 0,

_onPendingData: [Function: noopPendingOutput],

agent: Agent {

_events: [Object: null prototype],

_eventsCount: 2,

_maxListeners: undefined,

defaultPort: 443,

protocol: 'https:',

options: [Object],

requests: {},

sockets: [Object],

freeSockets: {},

keepAliveMsecs: 1000,

keepAlive: false,

maxSockets: Infinity,

maxFreeSockets: 256,

scheduling: 'fifo',

maxTotalSockets: Infinity,

totalSocketCount: 1,

maxCachedSessions: 100,

_sessionCache: [Object],

[Symbol(kCapture)]: false

},

socketPath: undefined,

method: 'POST',

maxHeaderSize: undefined,

insecureHTTPParser: undefined,

path: '/openvidu/api/sessions',

_ended: false,

res: null,

aborted: false,

timeoutCb: null,

upgradeOrConnect: false,

parser: null,

maxHeadersCount: null,

reusedSocket: false,

host: 'localhost',

protocol: 'https:',

_redirectable: [Circular *2],

[Symbol(kCapture)]: false,

[Symbol(kNeedDrain)]: false,

[Symbol(corked)]: 0,

[Symbol(kOutHeaders)]: [Object: null prototype] {

accept: [Array],

'content-type': [Array],

authorization: [Array],

'user-agent': [Array],

'content-length': [Array],

host: [Array]

}

},

_currentUrl: 'https://localhost:4443/openvidu/api/sessions',

[Symbol(kCapture)]: false

}

Error: [object Object]

at /usr/src/app/node_modules/openvidu-node-client/lib/Session.js:471:28

at processTicksAndRejections (node:internal/process/task_queues:93:5)`



Thank you for your help.
