### ISSUE TITLE
Error ionic app in android with target sdk 30

### ISSUE THREAD

**Issue by alexpeke** [OpenVidu/openvidu-tutorials#171]
Hello, 

I have detected an error that occurs in your ionic demo, the problem is that android does not share the video correctly with a pc connected in the demo "https://demos.openvidu.io/basic-videoconference/" when we increase the android target sdk to 30.

Since november all applications must have sdk target 30 to be uploaded to the play store, in case of ionic:
"<preference name="android-targetSdkVersion" value="30" />"

Tested Devices:
Samsung A32 Android 11. Doesn't Work
Samsung A40 Android 11. Doesn't Work
Xiaomi Pocophone F1 Android 10. Works Fine
Xiaomi Mi11 Android 11. Works Fine

At the moment, the error only appears on samsung devices with android 11.

![Captura de pantalla 2022-01-17 172554](https://user-images.githubusercontent.com/62706709/149806954-babd1347-8ccb-4abe-97ad-493cc66948a0.png)

Thank you,

**Comment by CSantosM** [comment]
Hi, do you have any special error log which help us to fix this issue?

**Comment by alexpeke** [comment]
Thank you for the quick answer, 

When the video doesn't work I get this warning in PC console 
![Captura de pantalla 2022-01-18 130437](https://user-images.githubusercontent.com/62706709/149934382-8e50f9dd-1255-48d0-a20b-7d68cebbc47f.png)

And in Android side
![Sin título](https://user-images.githubusercontent.com/62706709/149935166-8152911d-e21c-4b1d-aa64-8779b2c20eae.png)

Thank you.

**Comment by gomez34** [comment]
Hi,
Same error here, to upload an app to the play store it is necessary to indicate sdk-target 30 since November, any solution?

Thanks.
