### ISSUE TITLE
OpenVidu Android : Not connecting to server, join room error

### ISSUE THREAD

**Issue by kuldeep-aadrika** [OpenVidu/openvidu-tutorials#175]
joinRoom() in CustomWebSocketListener : websocket hit gives the following error.

CustomWebSocketListener: Text Message {"id":0,"error":{"code":-1,"message":"java.lang.RuntimeException:joinRoom","data":"java.lang.RuntimeException: joinRoom\n\tat io.openvidu.server.rpc.RpcHandler.getStringParam(RpcHandler.java:811)\n\tat io.openvidu.server.rpc.RpcHandler.checkSdkVersionCompliancy(RpcHandler.java:892)\n\tat io.openvidu.server.rpc.RpcHandler.joinRoom(RpcHandler.java:302)\n\tat io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:126)\n\tat org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:142)\n\tat org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"},"jsonrpc":"2.0"}

I checked this on the RpcHandler.
the value for "sdkVersion" i.e ProtocolElements.JOINROOM_SDKVERSION_PARAM is not added in json.

Provide with a sample value for demo server connection as adding sdkVersion is giving following error.

CustomWebSocketListener: Text Message {"id":0,"error":{"code":-1,"message":"java.lang.RuntimeException:Version "29" of openvidu-browser does not comply with semver format","data":"java.lang.RuntimeException: Version "2.22.0" of openvidu-browser does not comply with semver format\n\tat io.openvidu.server.utils.VersionComparator.checkSemver(VersionComparator.java:35)\n\tat io.openvidu.server.utils.VersionComparator.checkVersionCompatibility(VersionComparator.java:22)\n\tat io.openvidu.server.rpc.RpcHandler.checkSdkVersionCompliancy(RpcHandler.java:895)\n\tat io.openvidu.server.rpc.RpcHandler.joinRoom(RpcHandler.java:302)\n\tat io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:126)\n\tat org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:142)\n\tat org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"},"jsonrpc":"2.0"}

**Comment by pabloFuente** [comment]
Hi,

This commit decreases the severity of the lack of this RPC parameter: https://github.com/OpenVidu/openvidu/commit/bc1d1b7925618881be129d3ebb05495e276391b3

To fix the problem, just add parameter "sdkVersion" with any value you want (to avoid warning or error logs in openvidu-server, provide the same version number as your OpenVidu deployment. Right here: https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-android/app/src/main/java/io/openvidu/openvidu_android/websocket/CustomWebSocket.java#L202
