### ISSUE TITLE
React Depenency OpenVidu-Browser and OpenVidu-React do not work properly on Google Chrome

### ISSUE THREAD

**Issue by bajie01** [OpenVidu/openvidu-tutorials#177]
For Google Chrome version 102.0.5005.61, the React depenency OpenVidu-Browser and OpenVidu-React encounter the following error ：
getMediaError: [object OverconstrainedError]
Publisher initialization failed. INPUT_VIDEO_DEVICE_NOT_FOUND: Video input device with deviceId '' not found

**Comment by ehddud1006** [comment]
I am having the same problem. 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/62373865/174624427-916ed3ea-1b6d-4a8d-914f-c77da37b415e.png">
deviceId = "" 
Why do I keep getting spaces in id?

**Comment by CSantosM** [comment]
getUserMedia will return an empty label attribute value if the permission for accessing the mediadevice is not given.
https://stackoverflow.com/questions/60297972/navigator-mediadevices-enumeratedevices-returns-empty-labels

**Comment by ehddud1006** [comment]
In Firefox, it asks for permission, but in Chrome it doesn't, and a blank space is inserted immediately. Chrome's microphone and camera access are allowed in the MacBook settings.

**Comment by ehddud1006** [comment]
As a temporary measure, I gave the video source: default value so that I could access my computer's webcam. 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/62373865/174628914-42e70098-66f3-42b4-9417-192861cade28.png">
