### ISSUE TITLE
Create custom video call user interface

### ISSUE THREAD

**Issue by asadmalik3** [OpenVidu/openvidu-tutorials#178]
Hi,

I am looking for a tutorial where I can build my own video call interface instead of using pre-build interfaces that comes out of the box. Is there a way to access raw stream object and bind it to HTML5 video player in OpenVidu?

Thanks

**Comment by CSantosM** [comment]
Hi, what is most likely to suit you is OpenVidu Components https://docs.openvidu.io/en/2.22.0/components/ 

By the way, use the OpenVidu Forum for question.
