### ISSUE TITLE
Failed to deploy the project front-end Websocket connection using the front - end separation mode 

### ISSUE THREAD

**Issue by zhou3037451663** [OpenVidu/openvidu-tutorials#180]
Vue3 framework is used for my front-end, openVidu version is 2.21.0.  The problem I have encountered is that after I packaged vUE and published it to the server, there was an error when I connected to openVidu service through websocket, but I could connect to the server normally by using local VUE. At present, this problem has bothered me for a long time. 
![image](https://user-images.githubusercontent.com/58869728/174221875-e0fa6ec3-0c59-49d9-8937-7a5fa06cf601.png)

**Comment by CSantosM** [comment]
I think this is related to your Vue application and not to OpenVidu so, unfortunately, we can't help you.
