### ISSUE TITLE
The tutorial openvidu-ipcamera project only shows loading emoticons

### ISSUE THREAD

**Issue by minjae9010** [OpenVidu/openvidu-tutorials#183]
The openvidu-ipcamera project has been executed by showing docs, but only loading emoticons have been shown Below is the docker server and the project log

Docker openvidu

![image](https://user-images.githubusercontent.com/49522093/182979928-05e11792-c94a-4919-9d74-293063fa01bf.png)
![image](https://user-images.githubusercontent.com/49522093/182979976-fb443f61-9408-498a-b59c-3bf5c683a1a1.png)
![image](https://user-images.githubusercontent.com/49522093/182979940-3080bd19-9c36-4057-b432-c77fdb2319f6.png)

ipcamera Project
![image](https://user-images.githubusercontent.com/49522093/182980115-c97c231f-b36d-4a96-a641-5d6d5a971166.png)

web Screen

![image](https://user-images.githubusercontent.com/49522093/182980044-13f7896b-50d9-4fde-b9a4-2b61e25d89d5.png)

**Comment by micaelgallego** [comment]
It seems Media server is not able to connect to RTSP server located in IP 193.147.62.13.

Regards
