### ISSUE TITLE
Custom components and features

### ISSUE THREAD

**Issue by list12318** [OpenVidu/openvidu-tutorials#191]
Hello, I have a question and would like to consult with you

I just want to use your view area, and I want to implement other functions based on your API. Currently, I am using Electron+React

May I ask how to switch your audio source? I only saw the method of switching video sources in your API documentation address, https://docs.openvidu.io/en/stable/advanced-features/switch-camera/ May I ask if there is a specific method document address available?

**Comment by CSantosM** [comment]
You will need to unpublish and publish your new stream with the properly audioDevice 
https://docs.openvidu.io/en/2.30.0/cheatsheet/publish-unpublish/#publishunpublish-a-stream

BTW, use the [community forum](https://openvidu.discourse.group/) for question please
