### ISSUE TITLE
How to share my screen?Could you give me  an example?

### ISSUE THREAD

**Issue by liujiaxiang** [OpenVidu/openvidu-tutorials#2]
I use this:
OV.initPublisher('html-element-id', { screen: true });

but i can't share screen.I use firefox.

**Comment by pabloFuente** [comment]
Hi:
1. Could you post here what messages you get on browser's console?
2. What version  of openvidu-browser and openvidu-server are you using? Try with 1.3.0 for both of them.
3. Have you checked the note at the bottom of [this page in the Docs](http://openvidu.io/docs/how-do-i/screen-share/)? In Firefox it is a mandatory requirement to **serve your page over HTTPS** for Screen Sharing to work even when you are using `localhost`.

**Comment by liujiaxiang** [comment]
The log is:
screen sharing is not available
WebRtcPeer.js:39:4
Request of SESSIONID and TOKEN gone WELL (SESSIONID:wss://localhost:8443/8jcs4k82765mo1f6jvj8kqa3ir, TOKEN:ippri1vs22ougcon2bhl1fj1kv)
session:73:2
