### ISSUE TITLE
Openvidu-ionic Consultation

### ISSUE THREAD

**Issue by ly3299297** [OpenVidu/openvidu-tutorials#21]
Can Openvidu-ionic realize the communication between Android and browser? Why can't the browser subscribe to the stream published by Android, Android seems to be able to subscribe to the stream published by the browser, but it can't be displayed, only the participant name Participant0

**Comment by micaelgallego** [comment]
openvidu-ionic should work seamless with openvidu-browser. If you have any connection problems between Android and a browser, please review that OpenVidu Server is correctly installed with TURN server.

**Comment by ly3299297** [comment]
What is seamless?The client and server are running in the company's internal network. Is TURN server influential?

**Comment by micaelgallego** [comment]
https://dictionary.cambridge.org/es/diccionario/ingles/seamless

If Android is not publishing, that is problem

**Comment by ly3299297** [comment]
How can I confirm TURN server is correctly,The Architectures is two,I am deploying server according to the official process
