### ISSUE TITLE
Openvidu-ionic

### ISSUE THREAD

**Issue by ly3299297** [OpenVidu/openvidu-tutorials#22]
What is the version of Android that Openvidu-ionic requires?

**Comment by micaelgallego** [comment]
In the doc https://openvidu.io/docs/tutorials/openvidu-ionic/ you can see this note:

> This Ionic application is implemented with Ionic v4-beta. This means that it is a preview version of Ionic 4 and that could cause sporadic problems. The moment final stable version of Ionic 4 is released, this project will be updated to use it. Bugs reported: Android 5 (Lollipop) and 6 (Marshmallow) will not work with Ionic v4-beta until this issue is solved.
