### ISSUE TITLE
Coturn

### ISSUE THREAD

**Issue by ly3299297** [OpenVidu/openvidu-tutorials#23]
I have Coturn Server and Openvidu server in Public network，but my client in private network,what's should I do?How do I configure coturn server on the client side?

**Comment by pabloFuente** [comment]
If you have deployed OpenVidu as stated in the docs, you don't have to do anything else. Coturn will automatically be used by your clients when necessary.

**Comment by pabloFuente** [comment]
Docker deployment is not supported. Use AWS deployment or Ubuntu deployment as stated in the docs.

**Comment by ly3299297** [comment]
You mean that Docker deployment not support coturn server,AWS deployment and Ubuntu deployment is supported.Is my understanding right?

**Comment by pabloFuente** [comment]
Yes. Dockerized OpenVidu Server is only supposed for demo and deployment environments, not production ones.

**Comment by ly3299297** [comment]
OK,thank you!!!!!

**Comment by ly3299297** [comment]
Do you plan to add docker deployment as production ones in subsequent releases?

**Comment by ly3299297** [comment]
I have a question.Here are your official deployment orders，This clearly uses docker deployment。
-------docker run -d -p 3333:3333 -e openvidu.secret=YOUR_SECRET -e openvidu.publicurl=https://my.openvidu.server.ip:3333 -e openvidu.cdr=true -e server.port=3333 -e KMS_STUN_IP=stun.l.google.com -e KMS_STUN_PORT=19302 -e KMS_TURN_URL=myuser:mypass@54.54.54.54:3478 openvidu/openvidu-server-kms:2.6.0

**Comment by pabloFuente** [comment]
We intend to provide a Docker-based deployment configuration in the future. Not in the short term, either way.
