### ISSUE TITLE
ionic android app production release build not working

### ISSUE THREAD

**Issue by devamit123** [OpenVidu/openvidu-tutorials#25]
Hi,

In my debug build it is working fine with live streams but with --prod --release build it gives blank white screen while creating streams.

Please help what should I change/update.

Thanks.

**Comment by micaelgallego** [comment]
It seems that ionic 4 will be released in January of 2019.

**Comment by pabloFuente** [comment]
@devamit123 I have tried `--prod --release build` in our openvidu-ionic tutorial following official Ionic v4 instructions: https://beta.ionicframework.com/docs/publishing/play-store

And it works just fine in an Android device. No difference at all with the debug version of the app. Streams are succesfully published and subscribed.
