### ISSUE TITLE
Coturn not working?????

### ISSUE THREAD

**Issue by ly3299297** [OpenVidu/openvidu-tutorials#26]
I deployed OpenviduServer on the Ubuntu of the private network in the way of official deployment.If my client is connected on the  private network, if my client is not connected on the  public network, what's the reason? Is coturn not working? What should I do?

**Comment by pabloFuente** [comment]
OpenVidu Server should never be deployed in a private, firewall-protected network if you intend to support external video conferences. Official documentation for Ubuntu deployment says coturn server should be deployed in the same host as OpenVidu Server. That means your coturn server would also be behind a restricted network, and by definition that doesn't make sense. coturn server always need to be in a public network.

It is possible to deploy OpenVidu Server in a private network if you use an external, publicly accessible coturn server and configure OpenVidu to use it, but that would mean that every media connection of external clients will be routed through the coturn server, which will impact performance and latency. Not a good idea.

**Comment by ly3299297** [comment]
You mean that both Openvidu Server and Coturn Server are deployed to the public network and on the same machine, my client can successfully connect to both public and private networks. Do I understand that correctly?

**Comment by pabloFuente** [comment]
Yes, that is the proper way to deploy OpenVidu. As documentation clearly says, these are the network requirements your host must meet:
https://openvidu.io/docs/deployment/deploying-ubuntu/#server-network-requirements
