### ISSUE TITLE
Self signed certificate configuration only on safari mobile not working

### ISSUE THREAD

**Issue by zlatnaspirala** [OpenVidu/openvidu-tutorials#29]
I run openvidu/server and KMS with single docker container.

I install coturn on my cent os 7 .

This is my command : 

> docker run -d --net="host" -e openvidu.secret=YOUR_SECRET -e openvidu.publicurl=https://MY_IP:4443 -e openvidu.cdr=true -e server.port=4443 -e KMS_STUN_IP=MY_IP -e KMS_STUN_P|
> ORT=19302 -e KMS_TURN_URL=myuser:mypass@MY_IP:3478 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/kurento/rec:/var/kurento/rec -e openvidu.recording=true -e MY_UID=$(id -u $USER) -e openvidu.|
> recording.path=/var/kurento/rec -e openvidu.recording.public-access=true openvidu/openvidu-server-kms:latest  

I run also coturn but with default certification.

**Node.js server for recording** activated with no problem for desktop browsers everything works fine.

**Everything works fine except safari mobile :**

Err in browser : 

WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.)
I found that 9807 describe cert chain .

It is very strange for one browser to allow without alert prompt access to the self sign cert site. I say yes but wss coming with problem.

Any suggestion.

I am also interest to know is turn_server.key/crt and openvidu cert for node.js server to different or must be the same certification ?

And did i need to enter in docker container to make some changes about CRT...

I want to use selfSign cert is not problem for development time. 

I also try to add this args but with this configuration nothing works: 

-e server.ssl.key-store=/var/kurento/node-server/YOUR_KEYSTORE_NAME.jks -e server.ssl.key-store-password=123456 -e server.ssl.key-alias=YOUR_KEYSTORE_ALIAS openvidu/openvidu-server-kms:latest

**Comment by zlatnaspirala** [comment]
What's wrong with server.ssl.key-store arg ? 

docker run -d --net="host" -e openvidu.secret=YOUR_SECRET -e openvidu.publicurl=https://MY_SUB_DOMAIN:4443 -e openvidu.cdr=true -e server.port=4443 -e KMS_STUN_IP=MY_SUB_DOMAIN -e KMS_STUN_PORT=19302 -e KMS_TURN_URL=myuser:mypass@MY_SUB_DOMAIN:3478 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/kurento/rec:/var/kurento/rec -e openvidu.recording=true -e MY_UID=$(id -u $USER) -e openvidu.recording.path=/var/kurento/rec -e openvidu.recording.public-access=true -e server.ssl.key-store=/etc/letsencrypt/live/MY_SUB_DOMAIN/YOUR_KEYSTORE_NAME.jks -e server.ssl.key-store-password=123456 -e server.ssl.key-alias=YOUR_KEYSTORE_ALIAS openvidu/openvidu-server-kms:latest

Safari desktop work , chrome not ?! Very unusual !   

https://MY_SUB_DOMAIN:4443. ( OPEN VIDE CERT !! ) 
https://MY_SUB_DOMAIN:5000 ( MY let encode x3 cert / GOOD) 

How to setup : server.ssl args ?

Usual when i setup server.ssl args nothing works .

Please help me to get out of this hell.

**Comment by pabloFuente** [comment]
I'm pretty sure Safari for iOS devices will reject secure websockets established under an invalid certificate.
There are many issues regarding this topic on the Internet: 

- https://stackoverflow.com/questions/36726858/ios-safari-fails-to-connect-to-secure-websocket-but-works-on-desktop
- https://github.com/jupyterhub/jupyterhub/issues/292
- https://stackoverflow.com/questions/4014055/how-to-debug-safari-silently-failing-to-connect-to-a-secure-websocket
- https://stackoverflow.com/questions/24341000/secure-websockets-not-working-on-iphone-browsers

So this isn't really an OpenVidu problem, but a problem with how strict Apple is about its browser and the connections it can establish. I guess the easiest solution is to deploy an OpenVidu Server with a valid certificate. If you want (**and under your sole responsibility**), you can use the public server available at https://demos.openvidu.io:4443/ to quickly test your app when developing it, but this is a non-secure and publicly accessible OpenVidu Server and you should really consider setting up your own OpenVidu Server with a valid certificate for your particular development environment.

**Comment by zlatnaspirala** [comment]
Ok i understand ,
 but please i just need this part with little more explanation : 

File keystore.jks must be in the project’s root path, and a file named applica- tion.properties must exist in src/main/resources/, with the following content:

server.port: 8443
server.ssl.key-store: keystore.jks
server.ssl.key-store-password: yourPassword

– You can also specify the location of the properties file. When launching your Spring-Boot based app, issue the flag -Dspring.config.location=<path-to-properties> .
• Start application

mvn -U clean spring-boot:run -Dkms.url=ws://kms_host:kms_port/kurento  


1) I need to know **how to stop** and run again java (openvidu server) ?
2) Is it ok to run recording part with this docker ( openvidu/openvidu-server-kms:latest ) ?

I am in openvidu/openvidu-server-kms:latest

**Comment by pabloFuente** [comment]
1. To stop openvidu-server process, just kill the Java process if you are running it as JAR file or remove openvidu/openvidu-server-kms docker container (`docker rm -f CONTAINER_ID`) if you are using the Docker container in your development environment.
2. OpenVidu recording module works fine with openvidu/openvidu-server-kms. Just make sure to follow the steps here stated: https://openvidu.io/docs/advanced-features/recording/#for-openvidu-server-docker-image-development-environment

By the way, make sure to run `docker pull openvidu/openvidu-server-kms:latest` to ensure you are in fact running the latest version of the container. If you already had a latest tagged container, newest _latest_ container won't be downloaded unless you force it with pull command.

Regarding the certificate configuration, the last 3 stystem properties here in OpenVidu Docs (https://openvidu.io/docs/reference-docs/openvidu-server-params/) are enough to run OpenVidu Server (whether it is the JAR artifact or the docker container artifact) with any custom certificate: `server.ssl.key-store`, `server.ssl.key-store-password`, `server.ssl.key-alias`

**Comment by zlatnaspirala** [comment]
Thanks , i pass all this 20 times .... 

I make it works on all browser also recording with selfsign but when i try to implement letEncrypt cert with **domain** and also add "`server.ssl.key-store`, `server.ssl.key-store-password`, `server.ssl.key-alias`" like args when i run docker  . ( generated from openvidu tutorial ) , nothing works .

DOMAIN:5000. Have nice CERT - valid .
DOMAIN:4443 have default cert openvidu and i have CA invalid name ....

**Comment by senakafdo** [comment]
Seeing your issue, your problem could be that you do not actually copy the generated JKS file into the docker container. When you provide the keystore path it refers to a path inside your container and not on your local filesystem. So, either mount your local path on to the container or use something like [docker secrets](https://docs.docker.com/engine/swarm/secrets/).

If you want to see some instructions, I've used in my project, see https://ove.readthedocs.io/en/latest/docs/INSTALLATION.html#using-your-own-certificates-for-openvidu.
