### ISSUE TITLE
Please improve code quality

### ISSUE THREAD

**Issue by daywednes** [OpenVidu/openvidu-tutorials#3]
I like the idea of openvidu but  looking through the code examples as well as the api code, i see they both have very bad quality. That leads me to the question if I can trust the api as well for building a high quality product.

**Comment by micaelgallego** [comment]
We try to do our best when creating OpenVidu. If you think there are things that can be improved, please be more explicit and, if you want, send as a Pull Request.

Regarding the tutorials, we have created the most simple code with the objective they are easy to understand. Tutorials are not intended to be production quality code.
