### ISSUE TITLE
Would it be possible to optionally use ws:// instead of wss:// via a Environment Variable?

### ISSUE THREAD

**Issue by senakafdo** [OpenVidu/openvidu-tutorials#30]
While `wss://` is great, it may not always be a requirement, especially in on-prem setups involving a Proxy/FW that does security with its own set of a certs etc.

**Comment by timorss** [comment]
I can't connect to wss, i tried to connect to ws and it tried to connect to wss anyway.
Here is the error:
Could not connect to wss://..../openvidu (invoking onerror if defined) Event {isTrusted: false}

**Comment by pabloFuente** [comment]
WebRTC will only work under HTTPS pages. And you cannot mix HTTPS and WS protocols. The browser will throw an error.

So yes, WSS is mandatory, and WS cannot be used.

**Comment by senakafdo** [comment]
@pabloFuente, I don't exactly recall what I reported this against - I'm sorry and I regret not making it absolutely clear to you at that point. However, if you take a look at https://github.com/OpenVidu/openvidu/search?q=wss&unscoped_q=wss, you will find a mixture of WS/WSS use. This I believe was related to something where WS could be used.
