### ISSUE TITLE
Problem when running the react-insecure tutorial

### ISSUE THREAD

**Issue by MohamedHajr** [OpenVidu/openvidu-tutorials#32]
After executing the instructions in the running this tutorial section  here https://openvidu.io/docs/tutorials/openvidu-insecure-react/

When I open the website and click join to start the video conferencing, I got this error

Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
App.js:294 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at App.js:294

Maybe the certificates on the server running in the docker container is expired?

**Comment by pabloFuente** [comment]
The instructions for running the tutorial states this:

> 5) Go to localhost:3000 to test the app once the server is running. The first time you use the docker container, an alert message will suggest you accept the self-signed certificate of openvidu-server when you first try to join a video-call.

Of course the certificate inside the docker container is not a valid one. It's a development / self-signed certficate. You must connect to `https://localhost:4443` first time you launch it to accept it. Once you do that, your connection to it will work fine.

**Comment by MohamedHajr** [comment]
I didn't see that my bad, thanks a lot for pointing it out
