### ISSUE TITLE
how can i switch iphone's front camera and back camera

### ISSUE THREAD

**Issue by oldRabbit1** [OpenVidu/openvidu-tutorials#36]
problem in use openvidu-ionic, i found that iphone's front camera and back camera can not be swithed. it default in use front camera,so how can i switch to the front camera,can someone help me?

**Comment by oldRabbit1** [comment]
can someone help me?

**Comment by oldRabbit1** [comment]
in this project, how can i switch iphone's front camera and back camera

**Comment by oldRabbit1** [comment]
i'm waitting online.....so so so so ....bla...bla.....

**Comment by micaelgallego** [comment]
Please don't create useless messages in bug reports.

**Comment by oldRabbit1** [comment]
> Please don't create useless messages in bug reports.

problem in use openvidu-ionic, i found that iphone's front camera and back camera can not be swithed.can you help me?

**Comment by micaelgallego** [comment]
It seems a bug in the Cordova-webrtc plugin. That project is not maintained any more by their original creators.

If this feature is important for your commercial use case, you can consider commercial support from OpenVidu team. If you are interested please send an email to openvidu@gmail.com

**Comment by oldRabbit1** [comment]
i'm using the Cordova-plugin-iosrtc,not the one you talk to me. did you ever know it?

**Comment by oldRabbit1** [comment]
> It seems a bug in the Cordova-webrtc plugin. That project is not maintained any more by their original creators.
> 
> If this feature is important for your commercial use case, you can consider commercial support from OpenVidu team. If you are interested please send an email to [openvidu@gmail.com](mailto:openvidu@gmail.com)

i'm using the Cordova-plugin-iosrtc,not the one you talk to me. did you ever know it?

**Comment by qjw2bqn** [comment]
Hello brother, what type of iphone is you using, and which version of the system is it, why didn't I run it successfully?
my question is：https://github.com/OpenVidu/openvidu-tutorials/issues/33

**Comment by oldRabbit1** [comment]
> @oldRabbit1
> Hello brother, what type of iphone is you using, and which version of the system is it, why didn't I run it successfully?
> my question is：#33

iphone 6s, the version of the system is ios 11

**Comment by qjw2bqn** [comment]
@oldRabbit1  which version of xcode？still not work properly.

**Comment by CSantosM** [comment]
The [cordova-plugin-iosrtc](https://github.com/OpenVidu/cordova-plugin-iosrtc) has been updated to Swift 4.2 and today it is possible to switch the cameras in iOS.

**Comment by ankit0409** [comment]
Still not woking @CSantosM Plugin is not download with below command on my terminal
 $ cordova plugin add https://github.com/OpenVidu/cordova-plugin-iosrtc.git

Please look into this

**Comment by CSantosM** [comment]
The official plugin is hosted in https://github.com/cordova-rtc/cordova-plugin-iosrtc so you should install it with  ``` cordova plugin add cordova-plugin-iosrtct ```

**Comment by ankit0409** [comment]
@CSantosM is this work for both front and back?
I am trying with cordova plugin add cordova-plugin-iosrtct I have below error

npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 'cordova-plugin-iosrtct' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404 
npm ERR! 404  'cordova-plugin-iosrtct@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple1/.npm/_logs/2020-01-08T14_03_04_118Z-debug.log

**Comment by CSantosM** [comment]
https://github.com/cordova-rtc/cordova-plugin-iosrtc#installation

**Comment by ankit0409** [comment]
@CSantosM I am running below command and switch camera from front to back but back camera is not open please help.
cordova plugin add cordova-plugin-iosrtc

**Comment by ankit0409** [comment]
@CSantosM  Any update on this.

**Comment by ankit0409** [comment]
Hi @CSantosM,

Why you missguide the developer. I ionic ios app we cant trun camera from front to back. 

your command is https://github.com/cordova-rtc/cordova-plugin-iosrtc#installation is not working.

**Comment by CSantosM** [comment]
Please stop being disrespectful to our team. You should mind your manners a little.
We know the problem you have, you don't have to comment on every issue every day.

We have test our app [openvidu-call-ionic](https://github.com/OpenVidu/openvidu-call-ionic) is working fine.

You can read the official documentation of [openvidu-call-ionic](https://openvidu.io/docs/demos/openvidu-call-ionic/), [switch-camera](https://openvidu.io/docs/advanced-features/switch-camera/) and how it works in [openvidu-call-ionic](https://github.com/OpenVidu/openvidu-call-ionic/blob/90ba04e581cb545be1649a4c0a0e5ca8248ac7eb/src/app/video-room/video-room.page.ts#L254-L283)

If you need special attention, you can open commercial support [here](https://openvidu.io/commercial)

**Comment by ankit0409** [comment]
I follow all steps but its not working.
