### ISSUE TITLE
What's the difference between OV.createSession() (server side) and OV.initSession() (client).

### ISSUE THREAD

**Issue by PaulNicolasHunter** [OpenVidu/openvidu-tutorials#37]
I'm trying to record my stream and I've come across this line number 275 and 278 [here](https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-recording-node/server.js)

the session object passed in the `OV.startRecording()` is from the client side. 

and here in the docs of the recording [node ref sheet](https://openvidu.io/docs/reference-docs/openvidu-node-client/) the session id is from `OV.createSession()`.

so, what's the difference between them? which one should choose to get the session ID, because when I used the `OV.createSession()`'s session ID, I got 404 error , which according to the docs and I quote _404: no session exists for the passed sessionId_ .

so this means that I should use the client's session ID?
if so then what's the use of server side session?

> a side node, I noticed that `Recording.OutputMode.INDIVIDUAL` and `RecordingMode.ALWAYS` doesn't work, the error says that cannot get INDIVIDUAL of undefined, I explicitly passed string 'INDIVIDUAL' and 'ALWAYS'.

any guesses on both of the errors?

**Comment by PaulNicolasHunter** [comment]
another thing I wanted to say that I can't access the sessionId from `OV.initSession()`, In the docs it is straight away given that `session.Id` is a property bu it gives undefined on accessing it.

**Comment by PaulNicolasHunter** [comment]
okay so what I conclude that, the session which server side makes constitutes to the one made by the client.

both have same purposes.

however, I think there is still a bug in `Recording.OutputMode.INDIVIDUAL` and `RecordingMode.ALWAYS`, because when i looked into the code I couldn't find those flags..

**Comment by pabloFuente** [comment]
Closing for deviation from the main subject. If you think there's still a bug regarding `Recording.OutputMode`, please open a new issue.
