### ISSUE TITLE
how to destroy another user session on webcomponent

### ISSUE THREAD

**Issue by AliTajari** [OpenVidu/openvidu-tutorials#38]
Hi
I want to destroy another user session in webcomponent with a button. How can i do this?

**Comment by CSantosM** [comment]
Hello @AliTajari 
Nowadays the webcomponent tutorial can not do that. However you can get a [moderator token](https://openvidu.io/api/openvidu-node-client/enums/openvidurole.html#moderator) and assign it to the webcomponent. 

Like that:
```<openvidu-webcomponent session-config='{"sessionName":"SessionA", "user":"User1", "token": "TOKEN_RETRIEVED_FROM_OPENVIDU_SERVER"}'></openvidu-webcomponent>```

After that, you should create a button or whatever you want to manage and destroy the others session
