### ISSUE TITLE
What if end user using openvidu-browser get out of power suddenly?

### ISSUE THREAD

**Issue by Wrufesh** [OpenVidu/openvidu-tutorials#4]
I am following openvidu-node-client example. Here when user leaves the browser or closes the tab the js client make api request to node-server client to remove session and tokens being used.

But what if end user suddenly gets out of power and suddenly computer shuts down.

Is there any way to catch that event?

**Comment by pabloFuente** [comment]
Hi,

Right now OpenVidu Server doesn't support an event-based system for registering this kind of circumstances. Of course OpenVidu Server will be aware of the event and internal entities will be updated when the ping process doesn't receive the signal from the disconnected participant.
But to support sending this events to any application backend would suppose an important change in architecure, by providing an optional WebSocket or maybe making use of recently released HTTP2 events.

But we have in mind a pretty simple solution: in future releases we plan to provide an HTTP endpoint where to ask for Session's information, so devs can implement their own pulling procedure if they want to.

Regards.

**Comment by pabloFuente** [comment]
Hi,

Yes, you're right. Upon unexpected participant disconnection no connectionDestroyed event is sent. This is a bug that is already fixed in version 2.0.0, which will be available in the following days.

**Comment by Wrufesh** [comment]
I am desperately waiting version 2.0.0. 
I also found that the just joined client session's `connectionCreated` event is triggered for all those other clients which are disconnected (by power failure i.e without calling *`session.disconnect()`*) 

And: _Upon unexpected participant disconnection no connectionDestroyed event is sent._ 

Are both above behavior related to same issue?

What I wanted to achieve was to detect real time connection status of other participants in the session.
May be I am taking wrong approach. Is there any another way to achieve this?

Like using kurento javascript JSON-RPC client along with openvidu-node-client

Or can I see the commit fixing above issues.

**Comment by pabloFuente** [comment]
Hi,

Both behaviours are related. The fix just consists on making sure that the disconnected participant is removed from the proper session. It is done in [this method](https://github.com/OpenVidu/openvidu/blob/67e3578ea766355312730311f7541dd14fea9bc7/openvidu-server/src/main/java/io/openvidu/server/rpc/RpcHandler.java#L301).

We have had some problems with our CI environment, so release 2.0.0 may be delayed till next week. Sorry for the inconvenience.

**Comment by Wrufesh** [comment]
Ok great to hear that it would be releasing soon.

Meanwhile I compiled the master branch and tried it. Doing so I was able catch connectionCreated and connectionDestroyed event as desired.

But I cannot record the session. Seems openvidu-node-client code has been changed. I cannot build the token at first. `It says TokenOption class has no Builder.`

Can you please give me the quick instruction on how can I do recording with the openvidu-node-client of master branch.
That would be so grateful. :)

**Comment by pabloFuente** [comment]
Yes, that's because openvidu-node-client API has breaking changed. 

1) We have abandoned the Builder strategy for node client, as it doesn't make much sense (it was a quick way of sharing method structures with openvidu-java-client, but JavaScript code should use objects instead of Builders).

2) All callback mehtods have been refactored to Promise methods. Also, now the async method is OpenVidu.createSession, not Session.getSessionId (Session.generateToken remains async)

3) All "Archive" classes and mehtods are now named "Recording"

Maybe there are more breaking changes that I cannot explain right now, but all of them will be clearly stated in Release Notes of 2.0.0. Also take into account that more commits are coming to openvidu repo before relase.

Regards

**Comment by pabloFuente** [comment]
OpenVidu 2.0.0 now properly sends `connectionDestroyed` events uppon unexpected participant disconnection. You can also take advantage of new `reason` property for events [connectionDestroyed](https://openvidu.io/api/openvidu-browser/classes/connectionevent.html#reason), [streamDestroyed](https://openvidu.io/api/openvidu-browser/classes/streamevent.html#reason) and [sessionDisconnected](https://openvidu.io/api/openvidu-browser/classes/sessiondisconnectedevent.html#reason).
