### ISSUE TITLE
iOS swift4.0

### ISSUE THREAD

**Issue by echooooooo** [OpenVidu/openvidu-tutorials#44]
condition:
1.xcode 10.2
2.ios 12.1

Is there any support for swift 4.0  or above now?

**Comment by CSantosM** [comment]
Hey @echooooooo, [cordova plugin iosrtc plugin](https://github.com/OpenVidu/cordova-plugin-iosrtc.git) has been updated to: 

-  **Swift 4.2** 

and tested on:
-  **xcode 10.2.1** 
-  **iOS 12.2**

Use ``` cordova plugin add https://github.com/OpenVidu/cordova-plugin-iosrtc.git ``` to install it.
