### ISSUE TITLE
firebase deploy

### ISSUE THREAD

**Issue by yognam** [OpenVidu/openvidu-tutorials#46]
When we build --prod and deploy in firebase [https://webrtc-5f0f0.firebaseapp.com](https://webrtc-5f0f0.firebaseapp.com) it gives problem

**Comment by micaelgallego** [comment]
Can you describe the problem you have?

**Comment by yognam** [comment]
1. accessAllowed: false
   2. accessDenied: true
   3. canPlayListener: ƒ ()
   4. ee: EventEmitter {_events: {…}}
   5. isSubscribedToRemote: false
   6. lazyLaunchVideoElementCreatedEvent: false
   7. openvidu: OpenVidu {publishers: Array(1), secret: "", recorder: false
   , advancedConfiguration: {…}, webrtcStatsInterval: 0, …}
   8. permissionDialogTimeout: 14
   9. properties: {audioSource: undefined, frameRate: 30, insertMode:
   "APPEND", mirror: false, publishAudio: true, …}
   10. remote: false
   11. session: Session {streamManagers: Array(2), remoteStreamsCreated: {…}
   , isFirstIonicIosSubscriber: false, countDownForIonicIosSubscribers:
   false, remoteConnections: {…}, …}
   12. stream: Stream {ee: EventEmitter, isSubscribeToRemote: false,
   isLocalStreamReadyToPublish: false, isLocalStreamPublished: false,
   publishedOnce: false, …}
   13. videos: (2) [{…}, {…}]
   14. __proto__: StreamManager
   15. The publisher and the video element gets created but it doesn't
   publish the session.
   16. i have attached the publisher data above.
   17.

**Comment by yognam** [comment]
what i am doing now is that i have installed nginx and use that for
redirecting purpose but when i try to access through my ip on the same port
it doesn't work.

**Comment by yognam** [comment]
i quit with firebase
