### ISSUE TITLE
How could I make the ios platform use Swift superior to swift 3?

### ISSUE THREAD

**Issue by evilword666** [OpenVidu/openvidu-tutorials#48]
I am seeing that when I generate the ios platform the swift version that it uses is swift 3, however, the latest version of Xcode (Xcode 10.2.1 onwards) does not have support for swift 3.
Is it possible to make the ionic openvidu project generate the platform with swift 4 or higher?

**Comment by evilword666** [comment]
<img width="422" alt="Captura de Pantalla 2019-07-18 a la(s) 11 49 37" src="https://user-images.githubusercontent.com/10425457/61476254-3c901a00-a952-11e9-8961-4c2fe61afb08.png">

**Comment by CSantosM** [comment]
Hello @evilword666 , 
You can try to modify [this file](https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-ionic/hooks/iosrtc-swift-support.js) with `SWIFT_VERSION = '4.2'` and `BUILD_VERSION = '11.0'`.

**Comment by evilword666** [comment]
Hi @CSantosM  

I have tried what you mention but I get the following error.
Also the screen of my iphone stays white

<img width="868" alt="Captura de Pantalla 2019-07-19 a la(s) 16 39 43" src="https://user-images.githubusercontent.com/10425457/61567177-485c0900-aa44-11e9-80df-f8bb46b1a2f2.png">

**Comment by CSantosM** [comment]
We tested the changes and it works. 
Please, check our repository and run the app in a clean environment (remove the ios platform and rebuild with `ionic cordova prepare ios`).

**Comment by evilword666** [comment]
I have tried to compile the latest version of the app and when I emulate in the browser (ionic serve --lab) I get the following error:
<img width="1281" alt="Captura de Pantalla 2019-07-22 a la(s) 9 50 47" src="https://user-images.githubusercontent.com/10425457/61642987-93099b00-ac67-11e9-9b42-f9052a0c6024.png">

**Comment by evilword666** [comment]
I opened it in incognito mode and it works !!!
Thank you.
P.S. It also compiled well on my iphone
:)
