### ISSUE TITLE
"Connection not found for connectionId undefined owning endpoint d4nd8ugp5huwrl1c. Ice candidate will be ignored: [object Object]"

### ISSUE THREAD

**Issue by evilword666** [OpenVidu/openvidu-tutorials#49]
"Connection not found for connectionId undefined owning endpoint d4nd8ugp5huwrl1c. Ice candidate will be ignored: [object Object]"

I have managed to compile the ionic app, however, the following console errors appear to me:

<img width="979" alt="Captura de Pantalla 2019-07-22 a la(s) 17 15 41" src="https://user-images.githubusercontent.com/10425457/61669205-d33b3e80-aca4-11e9-9cc2-e491e1041445.png">

Is this normal?

**Comment by evilword666** [comment]
P.S. I cannot establish a connection with another client to make a videoconference

**Comment by CSantosM** [comment]
Hello @evilword666 , 
We've tested to launch openvidu-ionic with  `ionic serve` and `ionic serve --lab` and it works correctly.  We be able to deploy and join into a session without any problem connecting to our server in `https://demos.openvidu.io:4443` . So please, check your [server deployment](https://openvidu.io/docs/deployment/deploying-aws/) because it looks like an error when trying to connect the application to the server

**Comment by evilword666** [comment]
I am not using AWS, what I did was change the openvidu-browser 2.10.0 library to version 2.8.0 and with that I can already connect

**Comment by santoshsaven** [comment]
![image](https://user-images.githubusercontent.com/53169724/65666990-71100880-e05c-11e9-8301-561fa0a9a735.png)


getting this issue can you please guid me

**Comment by CSantosM** [comment]
Have you tested our [openvidu-ionic app](https://openvidu.io/docs/tutorials/openvidu-ionic/)?

Have you made sure that it works?

**Comment by santoshsaven** [comment]
yes it is alredy working for some one. i get the code from their repository only. while i am running in my machine i am getting this issue.

**Comment by CSantosM** [comment]
You have got a couple of things to keep in mind:

1. You're using **openvidu-browser 2.6.0**. Our lasest version available is **2.11.0**. 
2. As you know, our tutorials is using **Ionic 4**. We haven't tested with **Ionic 3** yet.

We strongly recommed you to clone the [openvidu-tutorials](https://github.com/OpenVidu/openvidu-tutorials) repository updated.

Regards
