### ISSUE TITLE
Is OpenVidu 1.9 not compatible with iphone safari?

### ISSUE THREAD

**Issue by sowmiyaksr** [OpenVidu/openvidu-tutorials#5]
Hi,

Recently, I have upgraded Openvidu Server 1.7 to 1.9.0-beta-1.

And I am using Openvidu-mvc-java, deployed in Ubuntu 16.04 with KMS 6.7 and Coturn.

Added the Openvidu-browser-1.9.0-beta-1.js in Openvidu-mvc-java "static" folder.
Changed the version in session.html

Changed openvidu-java-client to 1.8.0 in pom.xml.

Clean compile and package and run.

I am able to get the client side and remote videos in Chrome, Mozilla, Safari 11.0.1 in HighOS Sierra.

But the same not working for iphone Safari 11.0.3, checked in iphone 7 and 10.

So, is there anyother change, specific to get this in iPhone?

**Comment by sowmiyaksr** [comment]
Thank you. Advance thanks for 2.0.0

**Comment by sowmiyaksr** [comment]
I have upgraded to openvidu 2.1.0. still not working on iphones. Please let me know, if I need to do any configuration change openvidu-server and openvidu-mvc-java to make it working on iphone Safari.

**Comment by micaelgallego** [comment]
We are still working on it. Safari is not still supported in OpenVidu

**Comment by sowmiyaksr** [comment]
Is it possible to give , when can we expect the next update for iphone safari?

**Comment by pabloFuente** [comment]
OpenVidu 2.7.0 is now Safari compatible

**Comment by monavie1989** [comment]
I run openvidu 2.10.0 and it not working in iphone.
Some body help me
