### ISSUE TITLE
Path does not exist 

### ISSUE THREAD

**Issue by rizwan92** [OpenVidu/openvidu-tutorials#51]
Hii
I am using these dependencies 
```
    "axios": "^0.19.0",
    "openvidu-browser": "^2.11.0",
    "openvidu-node-client": "^2.11.0",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-webrtc": "^1.75.0"
```
My code is App.js 
https://gist.github.com/rizwan92/52ad61f28a97059d074eee8982e67408

I am facing this problem path does not exist in line number 25.

I tried installing react-native-webrtc by running command` npm install react-native-webrtc --save`

then I replaced line number 25 
from 
import { RTCView } from "./node_modules/openvidu-browser/node_modules/react-native-webrtc";
to 
import { RTCView } from "react-native-webrtc";
then it is throwing an exception

```
ExceptionsManager.js:86 TypeError: Cannot read property 'transform' of undefined
This error is located at:
    in RTCVideoView (at App.js:318)
    in RCTView (at View.js:35)
    in View (at App.js:313)
    in RCTView (at View.js:35)
    in View (at App.js:312)
    in RCTView (at View.js:35)
    in View (at ScrollView.js:1007)
    in RCTScrollView (at ScrollView.js:1147)
    in ScrollView (at App.js:310)
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)
```
at line number 203

**Comment by micaelgallego** [comment]
openvidu-browser with react-native support is a commercial feature, not open source.

Please contact with us in https://openvidu.io/commercial if you need more details.
