### ISSUE TITLE
Cannot run fresh clone of the openvidu-library-angular tutorial

### ISSUE THREAD

**Issue by FXschwartz** [OpenVidu/openvidu-tutorials#52]
After cloning the tutorial and installing dependencies and then running with ng serve I get this error and can't go any further
![image](https://user-images.githubusercontent.com/16527593/63819915-cf868180-c90c-11e9-96ef-e9afd39aee38.png)

**Comment by pabloFuente** [comment]
Commit b6244192f10b93d9e8ab744c9c7d64b67f7bf802 fixes this issue (tutorial has been updated to Angular 8)
