### ISSUE TITLE
React native - npm install issues

### ISSUE THREAD

**Issue by jArecki444** [OpenVidu/openvidu-tutorials#53]
Hello!
I was trying to install react native tutorial project dependencies and I'm not able to do that. I've just cloned repo from https://openvidu.io/docs/tutorials/openvidu-react-native/
and I receiving a lot of error messages about operating system permission issues trying to execute npm install. I run this command via node.js command prompt as administrator. 
![2019-09-04_14h13_28](https://user-images.githubusercontent.com/22935742/64253733-2d732480-cf1e-11e9-8322-6f0fe842480e.png)

--
My setup:
 Node: v10.16.0
 react-native-cli: 2.0.1
 Windows 10

**Comment by CSantosM** [comment]
Hi @jArecki444 

That's weird. 
Have you tried to clean your environment and reintsall with:
```rm -rf node_modules```
```rm package-lock.json```
```npm install```

What is your npm version?

**Comment by jArecki444** [comment]
Hi @CSantosM, thank you for reply, unfortunately I tried this solution - without any result. 
npm version: 6.9.0

**Comment by micaelgallego** [comment]
Try using a folder path without spaces and smaller.

**Comment by CSantosM** [comment]
Hello @jArecki444, 
As [openvidu-react-native](https://openvidu.io/docs/tutorials/openvidu-react-native/) tutorial said and as you know,

 **React Native support is a paid feature. A special version of openvidu-browser library is needed for openvidu-react-native tutorial to work.**
You can contact with commercial support through openvidu@gmail.com to get it.

In the meantime, you can install latest realease of openvidu-browser with ```npm install openvidu-browser2.11.0``` and test that the app compiles and launches in your smartphone.

**Comment by jArecki444** [comment]
Hi @CSantosM I've installed this package as you said, but I'm not able to run "react-native run-android",  there is another issue with WebRTCModule. 
Thanks for help, can I do anything else to solve this problem?
![2019-09-05_09h41_14](https://user-images.githubusercontent.com/22935742/64322110-36b5cd00-cfc2-11e9-8e2d-fc4e522dbd42.png)

**Comment by CSantosM** [comment]
Sorry, I was wrong. 

You need **the special version of openvidu-browser library**  for openvidu-react-native tutorial to compile and launch it.

**Comment by Jayaprakash7** [comment]
@CSantosM what is the mean of special version of openvidu-browser ? should I pay for it, to Implement this in my project

**Comment by micaelgallego** [comment]
In order to sustain OpenVidu open source development, we provide some of its complements as commercial software. Please contact with openvidu [at] gmail.com for more information.

**Comment by Jayaprakash7** [comment]
Is this one time payment or I have to subscribe for every year?

**Comment by ajaygh** [comment]
@micaelgallego I have contacted commercial two times without any reply
