### ISSUE TITLE
React-native BuildFailed

### ISSUE THREAD

**Issue by jorenf** [OpenVidu/openvidu-tutorials#55]
I have done al the NPM Installs/updates. Than i try to run React-native run-android. When i do that i will get the following error`s.

#info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :WebRTCModule.
     Required by:
         project :app
      > Unable to find a matching configuration of project :WebRTCModule: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

**Comment by CSantosM** [comment]
Hello @jorenf ,
As [openvidu-react-native](https://openvidu.io/docs/tutorials/openvidu-react-native/) tutorial said and as you know,

**React Native support is a paid feature. A special version of openvidu-browser library is needed for openvidu-react-native tutorial to work.**
You can contact with commercial support through openvidu@gmail.com to get it.

Regards
