### ISSUE TITLE
Ionic router issue.

### ISSUE THREAD

**Issue by AkiraEndoGroup** [OpenVidu/openvidu-tutorials#57]
Hello,

Pulled below repos and added my own code, Login page.
https://openvidu.io/docs/tutorials/openvidu-ionic/

Issue summary:
Ionic4 router is not working properly.
- Added login button on src/app/dashboard/dashboard.page.ts
this.router.navigate(['/login']);

- Automatically added the routes on src/app/app-routing.module.ts
const routes: Routes = [
  { path: '', loadChildren: './dashboard/dashboard.module#DashboardPageModule' },
  { path: ':roomName', loadChildren: './video-room/video-room.module#VideoRoomPageModule' },
  { path: 'Login', loadChildren: './pages/login/login.module#LoginPageModule' },
];

When I click the login button, it goes to VideoRoomPage and appeared the modal, not login page. Please let me know the reason.

Log:
[WDS] Live Reloading enabled.
OpenVidu.js:68 'OpenVidu' initialized
OpenVidu.js:69 openvidu-browser version: 2.11.0
setting-up-modal.component.ts:116 initialize publisher

**Comment by micaelgallego** [comment]
You have a bug in your ionic code. Nothing to do with OpenVidu.

Just put a prefix in VideoRoom path to distinguish it from Login path. Or move VideoRoom path to latest one.
