### ISSUE TITLE
Openvidu-library-angular video options modal

### ISSUE THREAD

**Issue by FXschwartz** [OpenVidu/openvidu-tutorials#58]
Right now whenever you joinSession() there is a modal that opens up that gives the user options to select video and audio and avatar.

Is there a way to skip this section entirely? Just go straight to the video session?

**Comment by micaelgallego** [comment]
Hello @FXschwartz, I think it can not be disabled right now, but we will explore the possibility to make it optional. 

Thank you for the suggestion.

Please @CSantosM, can you take note of that?

**Comment by CSantosM** [comment]
Hello @FXschwartz, 
Of course you can customize **openvidu-library-angular.**

At the end of the [Configuring OpenVidu Angular](https://openvidu.io/docs/tutorials/openvidu-library-angular/#configuring-openvidu-angular) you can see the configure properties variable. 
Providing this variable to the component you will be able to customize it.

```
this.ovSettings = {
  chat: false,
  autopublish: true,
  toolbarButtons: {
    audio: true,
    video: true,
    screenShare: true,
    fullscreen: true,
    exit: true,
  }
};
```

Setting `autopublish` to **true**, the configuration modal will not appear.

Regards

**Comment by FXschwartz** [comment]
@CSantosM Thats really odd. I noticed the documentation mentioned something about that but I tried it and setting autopublish to true did NOT take the modal away.

Let me try playing around with it some more and make sure I'm not doing something wrong.

**Comment by FXschwartz** [comment]
@CSantosM That was it! I had a typo in my ovSettings.

Really appreciate the help!
