### ISSUE TITLE
openvidu-recording-node cannot record

### ISSUE THREAD

**Issue by dasbid** [OpenVidu/openvidu-tutorials#6]
Ubuntu installed since amazon container did not complete install
openvidu-mvc-node works on all devices so I tried the recording tutorial now
docker installed with docker daemon running

kurento server running

started openvidu with:
java -jar -Dopenvidu.recording=true -Dopenvidu.recording.path=/home/path/to/videofiles -Dopenvidu.recording.free-access=true -Dopenvidu.secret=[MY_SECRET]-Dopenvidu.publicurl=https://[myweb.site]:8443/ -Dserver.ssl.key-store=[/path/to/keystore.jks] -Dserver.ssl.key-store-password=[mykspass] -Dserver.ssl.key-alias=[myksalias] openvidu-server-1.9.0.jar &

ran the nodejs:
node server.js [myweb.site]:8443 [MY_SECRET]

I can see/hear other streams and they can see/hear

but when I click record :
Start recording WRONG: HTTP 400 (500)

console gives me:
Request URL: https://[myweb.site]:5000/api/recording/start
Request Method: POST
Status Code: 400 Bad Request
Remote Address: [myip]:5000
Referrer Policy: no-referrer-when-downgrade

**Comment by pabloFuente** [comment]
Hi. Can you post here the log of OpenVidu Server? I need to see which is the cause of that Internal Server Error.

And can you please elaborate a little more about "amazon container did not complete install"? What kind of problem did you have when deploying on AWS?

Thanks!

**Comment by dasbid** [comment]
[myweb.site-1525975701985.log](https://github.com/OpenVidu/openvidu-tutorials/files/1992762/myweb.site-1525975701985.log)

I was trying the AWS deploy from https://openvidu.io/docs/deployment/deploying-aws/
ising the https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.json file and had the rollback issue

then I tried to just install docker on a vm
and couldn't get the remote playback working 
so I installed from the ubuntu jar method

log file attached.

**Comment by pabloFuente** [comment]
That is the log of the browser. I need the log of OpenVidu Server (the JAR)

**Comment by dasbid** [comment]
oops where's the file located?
/var/log/cloud-init-output.log?

**Comment by pabloFuente** [comment]
If you have executed JAR artifact of OpenVidu Server as you stated: 

java -jar -Dopenvidu.recording=true -Dopenvidu.recording.path=/home/path/to/videofiles -Dopenvidu.recording.free-access=true -Dopenvidu.secret=[MY_SECRET]-Dopenvidu.publicurl=https://[myweb.site]:8443/ -Dserver.ssl.key-store=[/path/to/keystore.jks] -Dserver.ssl.key-store-password=[mykspass] -Dserver.ssl.key-alias=[myksalias] openvidu-server-1.9.0.jar &

Then no log file has been generated. The output of that jar command will be written on the shell you used to run it. To store the output in a text file, you have to replace `openvidu-server-1.9.0.jar &` with `openvidu-server-1.9.0.jar &> /PATH/TO/YOUR/LOG_FILE.log &`

**Comment by dasbid** [comment]
[openvidu.log](https://github.com/OpenVidu/openvidu-tutorials/files/1992971/openvidu.log)

node was printing out : App listening on port 5000
Removing user | {sessionName, token}={SessionA, ikhjzsm9pkaxiod3}
Problems in the app server: the SESSION does not exist
Getting sessionId and token | {sessionName}={SessionA}
New session SessionA
SESSIONID: wss://myweb.site:8443/jwq0t3he3tqrdp6n
TOKEN: iwfdmhoigda8hxf2
Getting sessionId and token | {sessionName}={SessionA}
Existing session SessionA
SESSIONID: wss://myweb.site:8443/jwq0t3he3tqrdp6n
TOKEN: 0xitpk07ncelpq82
Starting recording | {sessionId}=wss://myweb.site:8443/jwq0t3he3tqrdp6n
Starting recording | {sessionId}=wss://myweb.site:8443/jwq0t3he3tqrdp6n
Stoping recording | {recordingId}=undefined
Starting recording | {sessionId}=wss://myweb.site:8443/jwq0t3he3tqrdp6n
Deleting recording | {recordingId}=undefined
Getting recording | {recordingId}=undefined
Listing recordings
Starting recording | {sessionId}=wss://myweb.site:8443/jwq0t3he3tqrdp6n

thanks

**Comment by pabloFuente** [comment]
I see some log lines of type "Permission denied" when trying to create the recording file. Try setting `openvidu.recording.path` to a folder with write permissions (to do so you can run, for example, command `chmod -R 777 /YOUR/FOLDER`)

**Comment by dasbid** [comment]
folder was already 777, so I ran with sudo java -jar
that worked but when I started recording the second user's video froze and I had a 1kb mp4 file with session id as name
[openvidu-b.log](https://github.com/OpenVidu/openvidu-tutorials/files/1993073/openvidu-b.log)

thanks!

**Comment by dasbid** [comment]
so today I tried the 2.0.0 versions of tutorial files and server
recording started but it recorded the page and not the video streams
and stop, list and get gives  WRONG: HTTP 400 (404)

[7nuvno3jpkvpvzuy.zip](https://github.com/OpenVidu/openvidu-tutorials/files/1995952/7nuvno3jpkvpvzuy.zip)

**Comment by pabloFuente** [comment]
Okey, thats weird. The best way I can help is by replicating your scenario. So please tell me:

1) OS (version, please) where you are running everything
2) How you have installed and run KMS
3) What OpenVidu Server artifact are you using and which is the exact command to run  it
4) How you are compiling and running recording-node tutorial

This is the only way I may know what is happening

**Comment by dasbid** [comment]
fresh Ubuntu 16.04 on AWS install today for 2.0.0

followed this guide https://openvidu.io/docs/deployment/deploying-ubuntu/

sudo java -jar -Dopenvidu.recording=true -Dopenvidu.recording.path=/path/to/videofiles -Dopenvidu.recording.free-access=true -Dopenvidu.secret=MY_SECRET-Dopenvidu.publicurl=https://myweb.site:4443/ -Dserver.ssl.key-store=keystore.jks -Dserver.ssl.key-store-password=MY_SECRET -Dserver.ssl.key-alias=myalias openvidu-server-2.0.0.jar &> /home/ubuntu/openvidu/openvidu.log &

ran the nodejs example with:
node server.js 55.55.55.55:4443 MY_SECRET

**Comment by pabloFuente** [comment]
I have followed step by step those exact instructions. My recordings are OK.

**_Everything as 'ubuntu' user:_**

I have launched a fresh-clean EC2 Ubuntu 16.04 in Amazon (_large_ size), installed KMS and COTURN just as stated in [OpenVidu documentation](https://openvidu.io/docs/deployment/deploying-ubuntu/), also installed Docker CE (for recordings, carefully setting it to not require root privileges) and node (for tutorial), and finally started openvidu-server-2.0.0.jar configured like this:

```
java -jar -Dopenvidu.secret=MY_SECRET -Dopenvidu.publicurl=https://AWS_IP:4443/ -Dopenvidu.recording=true -Dopenvidu.recording.path=/home/ubuntu/recordings -Dopenvidu.recording.public-access=true openvidu-server-2.0.0.jar &> ./openvidu.log &
```

I have started **openvidu-recording-node** like this: 

```
git clone https://github.com/OpenVidu/openvidu-tutorials.git
cd openvidu-tutorials/openvidu-recording-node
npm install
node server.js localhost:4443 MY_SECRET
```

When I connect to `https://AWS_IP:443/` I can test the application and start a recording without any problem. After a while I stop it and I get in the ouput the url where to access my recording directly from the browser (as I configured openvidu-server with `openvidu.recording.public-access=true`:

![selection_180](https://user-images.githubusercontent.com/15049534/39937398-df4d4964-554f-11e8-9b79-c2a2669bd2ad.png)

The recording looks pretty good, I can call every REST operation in the tutorial, included the Delete one (the files are properly removed from the EC2 machine).

I'm afraid I cannot do more. Look if there's something you have missed in any of the steps. To install Docker I have run this command:

```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get -y install docker-ce

sudo groupadd docker && sudo usermod -aG docker ${USER} # restart the shell for this command to have effect
```

I have installed node with this one:

```
sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
sudo apt-get install -y nodejs
```

**Comment by dasbid** [comment]
I think I needed the line for docker to run in sudo
sudo groupadd docker && sudo usermod -aG docker ${USER} 

sorry about that, new to docker :)
it's working now

but I still have to run JAVA with sudo:
sudo java -jar -Dopenvidu.secret=.....

or else it complains about docker container

thanks a bunch
