### ISSUE TITLE
Can not stream video from app to web and vice versa

### ISSUE THREAD

**Issue by robertle2812** [OpenVidu/openvidu-tutorials#60]
On Android I can use video conference perfectly between Android devices, but I can not see my streamed video from Android on another platforms (IOS, Web). I use OpenVidu nodejs tutorial  and sample app on iPhone connect to same kurento media (same port and secret key) but it not show.
Could you help me troubleshoot this problem please?

Thank you very much.

**Comment by micaelgallego** [comment]
Please describe which communications are ok and which are not. For example:

Web <-> Web: OK
Native Android <-> Native Android: OK
Native Android -> Web: FAIL
Web -> Native Android: OK
Ionic Android -> Web: OK

and so on...

**Comment by micaelgallego** [comment]
Please describe how are you deployed OpenVidu server and what is your network topology

**Comment by robertle2812** [comment]
Hi @micaelgallego 
I have installed Kurento and run OpenVidu server, OpenVidu js node on same server (with SSL certificate), when I access to server nodejs it work OK, on Android it also work OK, but with same session name when join on Android and web, I still can not see remote video on web and vice versa.

Thank you very much.

**Comment by robertle2812** [comment]
Hi @micaelgallego 
I found a bug in OpenVidu, When I access api https://my_domain:4443/api/sessions (with GET method) to view all sessions, I discovered all sessions name on web and device (Android) not synced. I tried  using a session ID created by browser and join Android device to that session -> It works but I only saw a black camera (from remote user) with name of participant joined (on Android) and on web another user will can not login with previous session name( click login button and nothing happen), but on Android device I still see their new session (I only see participant name and a black camera)

I include my session list below:
`"numberOfElements": 2,
    "content": [
        {
            "sessionId": "gmexigpq5twppg8p",
            "createdAt": 1572417371523,
            "mediaMode": "ROUTED",
            "recordingMode": "MANUAL",
            "defaultOutputMode": "COMPOSED",
            "defaultRecordingLayout": "BEST_FIT",
            "customSessionId": "",
            "connections": {
                "numberOfElements": 10,
                "content": [
                    {
                        "connectionId": "jnxi819gl8qdxpfi",
                        "createdAt": 1572422866460,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=jqgwhup6qdbpjtoy&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Hehe\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "ak1rr46zops6i7wa",
                        "createdAt": 1572422545279,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=rlmrkotqtsbaonfo&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 90\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "itrd8pitikxld4gl",
                        "createdAt": 1572421625968,
                        "location": "unknown",
                        "platform": "Chrome 78.0.3904.70 on Windows 10 64-bit",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=raxveh07mxpdz8tb&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"quyen le\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "mwzkdgewbjgnix6o",
                        "createdAt": 1572422553662,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=vo527vuuvmkiyhs5&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 90\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "cji47qvwln26jkez",
                        "createdAt": 1572422855933,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=flbia3cor8uezeir&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 90\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "zsdbqlrmq4xnt83h",
                        "createdAt": 1572422928984,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=t8pmbveuoufjfbgc&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Hehe\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "yferp1khsnulrkfw",
                        "createdAt": 1572422854485,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=ezw3gronlso3noro&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 90\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "e5mgtstskxesaqdw",
                        "createdAt": 1572422547249,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=jruvmklcg8hmvvof&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 90\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "lbqffpj9n6sqwer5",
                        "createdAt": 1572422538882,
                        "location": "unknown",
                        "platform": "Chrome Mobile 77.0.3865.92 on Android 9",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=fy1fony5trrobwa2&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 90\"}",
                        "publishers": [],
                        "subscribers": []
                    },
                    {
                        "connectionId": "z19919lq5ucr2adn",
                        "createdAt": 1572417372293,
                        "location": "unknown",
                        "platform": "Chrome 78.0.3904.70 on Windows 10 64-bit",
                        "token": "wss://mydomain.com:4443?sessionId=gmexigpq5twppg8p&token=iu2wr9nbljxe03oa&role=PUBLISHER&version=2.11.0",
                        "role": "PUBLISHER",
                        "serverData": "{\"serverData\":\"publisher1\"}",
                        "clientData": "{\"clientData\":\"Participant 71\"}",
                        "publishers": [],
                        "subscribers": []
                    }
                ]
            },
            "recording": false
        },
        {
            "sessionId": "pqglocg8alatowh0",
            "createdAt": 1572422184193,
            "mediaMode": "ROUTED",
            "recordingMode": "MANUAL",
            "defaultOutputMode": "COMPOSED",
            "defaultRecordingLayout": "BEST_FIT",
            "customSessionId": "",
            "connections": {
                "numberOfElements": 0,
                "content": []
            },
            "recording": false
        }
    ]
}`

**Comment by robertle2812** [comment]
By using https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-insecure-js this problem is resolved. I could stream video from app to web.
Thanks @micaelgallego
