### ISSUE TITLE
openvidu-library-angular - NullInjectorError: No provider for tae!

### ISSUE THREAD

**Issue by FXschwartz** [OpenVidu/openvidu-tutorials#61]
This works perfectly on my local machine. Its only when I build angular `ng build --prod` and pull it onto my staging server does it fail.

I've attached a screenshot of the error that gets repeated.

It appears the the session and token are both getting created correctly, but its after that when it fails. Going off of my console.logs it stops right whenever logs would normally start to show up from the openvidu files.

Hopefully this is something very simple that I am overlooking. Any help would be greatly appreciated.

Let me know if there is any more information I can provide to help.

![Screenshot_20191029_230340](https://user-images.githubusercontent.com/16527593/67828490-994ab700-faa1-11e9-8306-ca9846e3cef2.png)

**Comment by FXschwartz** [comment]
Just confirmed that if I do an Angular build with `ng build --prod=false` instead of `ng build --prod=true` then it works just fine.

So for some reason whatever Angular does to optimize with the --prod build is causing issues.

**Comment by FXschwartz** [comment]
Hey team I know things get super busy just wondering expectation wise if this is something that would be able to be looked at in the next week or so. As it stands we cannot build our Angular app using the production flag. If it is not something that can be looked at or handled in the next couple of weeks I will need to start looking at alternative solutions.

Again I know things get busy, let me know if there is anymore information I can provide to help.

**Comment by micaelgallego** [comment]
HI @FXschwartz, we are busy right now with other things. 

openvidu-library-angular is an open source library, it is very small and does not have a lot of source code. Contributions are welcomed. If you provide a PR we will review it.

**Comment by FXschwartz** [comment]
@micaelgallego Completely understand. I'll try and free up some time this weekend to take a wack at it.

Thanks

**Comment by FXschwartz** [comment]
Spent my free time this weekend trying to track down this issue,  leaving this here in case anyone else is running into this error and wants to help.

I was able to track down the location its happening at. The problem appears to be coming from the VideoRoomComponent which I believe belongs to the openvidu-call package, and that openvidu-library-angular uses.

The actual error is No provider for MatDialog. Although so far I can't see where there is a problem. The dialog boxes that the component is using are included in the provider's array of the module.

I'll post an update if I'm able to figure anything else out.

**Comment by CSantosM** [comment]
Fixed in [commit](2f3a7577e7e4526481f5af122ebf623050e63842). Merged to master.
