### ISSUE TITLE
It would be nice to have a Vue example.

### ISSUE THREAD

**Issue by gotexis** [OpenVidu/openvidu-tutorials#63]
Great job for all of the devs on this wonderful project! Because Vue is becoming very popular, also because of personal preference, I am currently trying to adapt the React project to Vue, but because of my limited knowledge of the `openvidu`, it would be great if this is on the official roadmap, or I can get some help with this process.

**Comment by micaelgallego** [comment]
Yep... it would be nice. But we are an small team and this is not our priority. It is in the roadmap...

**Comment by gotexis** [comment]
@micaelgallego Thanks for your response.

If there is anything I can do to help, please let me know. I don't have time to completely design one from scratch, but I can surely make contributions

**Comment by CSantosM** [comment]
Close because of it’s not an issue.
