### ISSUE TITLE
openvidu-library-angular - Fresh clone of tutorial does not work on firefox

### ISSUE THREAD

**Issue by FXschwartz** [OpenVidu/openvidu-tutorials#64]
Cloning the project and running it with the amazon openvidu stack works on chrome, and Safari, but not Firefox. When joining the it shows that there are two people in the session but not video or audio.

The only error in the console is `ICE failed`

![image](https://user-images.githubusercontent.com/16527593/68142603-61a29b80-fef5-11e9-89ed-0d6f3345ee40.png)

**Comment by paulvi** [comment]
If both participants are in the same LAN, than where is the server and does it has ICE/STUN services should not matter, 
as this is exactly what WebRTC for enable p2p connection.

If it works for Chrome+Chrome or Chrome+Sfari, but not in combination with Firefox,  
then exact versions of browsers used may help later.  
Can be issue of Firefox, but before it should be conformed with KITE testing
https://github.com/webrtc/kite

**Comment by CSantosM** [comment]
Prepared OpenVidu Call 2.13.0, merged changes into master. 
Working on Firefox. 
Will be included in OpenVidu Call 2.13.0 release.
