### ISSUE TITLE
Do OpenVidu server needs a Kurento server running?

### ISSUE THREAD

**Issue by fearchannel** [OpenVidu/openvidu-tutorials#65]
Why can't I just use the OpenVidu Server? I mean, we need some performance in our application, and running two servers may ruin it.

Do I always need Kurento and OpenVidu?

**Comment by micaelgallego** [comment]
Please use OpenVidu forum for questions. Use GitHub issues only for issues.

By the way, Kurento Media Server manages media and OpenVidu server manages signaling.
