### ISSUE TITLE
Openvidu Docker issue 

### ISSUE THREAD

**Issue by JeyakumarThangaraj** [OpenVidu/openvidu-tutorials#66]
Team,
Facing error while running below docker command

docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.11.0

Error:
Unable to find image 'openvidu/openvidu-server-kms:2.11.0' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: EOF.
![image](https://user-images.githubusercontent.com/49137580/68680926-87721500-0573-11ea-8064-48d488ab0c2a.png)

**Comment by micaelgallego** [comment]
It seems you have a problem with your Docker installation. Docker image is in Docker Hub and should be downloaded when executing "docker run" command...
