### ISSUE TITLE
openvidu-android and openvidu-electron interconnection issues

### ISSUE THREAD

**Issue by Aroxed** [OpenVidu/openvidu-tutorials#67]
Hello.
I've run android tutorial along with electron one. The Electron app shows both window (self and android's) and I can hear what android user says. But Android app is mute and can show its own camera only. What should I do to hear and show user from Electron app in Android app?

Thanks in advance.
Andrii.

**Comment by micaelgallego** [comment]
Please test these scenarios:
OpenVidu android app <--> OpenVidu web
OpenVidu electron app <--> OpenVidu web 

Report the results to see if problem is related with android or with electron app.

**Comment by Aroxed** [comment]
But I'd like to know if the current Android app (openvidu-android) should see the Electron app camera  window? Or it is not implemented?
Thanks.

**Comment by CSantosM** [comment]
Sure, they should work together.

**Comment by Aroxed** [comment]
Android-Android emulator works fine and Android-Electron works fine!
Thanks guys for great work.
