### ISSUE TITLE
Select item of RCTView and zoom this item

### ISSUE THREAD

**Issue by truongluuxuan** [OpenVidu/openvidu-tutorials#76]
In my code `  <RTCView
                                                            zOrder={0}
                                                            objectFit="cover"
                                                            // style={styles.remoteView}
                                                            style={{ width: this.state.rong, height: this.state.cao }}
                                                            ref={(rtcVideo) => {
                                                                if (!!rtcVideo) {
                                                                    item.addVideoElement(rtcVideo);
                                                                }
                                                            }}
                                                        />` after "addVideoElement" I want click a videoElement and zoom only it. Please bro help me

**Comment by CSantosM** [comment]
Hello @truongluuxuan ,

This is not an OpenVidu issue, perhaps the React forum could help you. 

Regards.
