### ISSUE TITLE
Error OpenVidu Angular Library ScreenShare

### ISSUE THREAD

**Issue by melvingilberto** [OpenVidu/openvidu-tutorials#77]
Openvidu angular library has error sharing screen and video camera, when one gives the exit button it seems that the screen transmission continues to emit according to the browser and the screen sharing button only appears when one maximizes the camera video

**Comment by CSantosM** [comment]
Prepared OpenVidu Call 2.13.0, merged changes into master.
Working on Firefox.
Will be included in OpenVidu Call 2.13.0 release.
