### ISSUE TITLE
Problem with session.connect and token in openvidu-mvc-java

### ISSUE THREAD

**Issue by dustgrinder** [OpenVidu/openvidu-tutorials#8]
I have updated to Openvidu 2.0.0. In your MVC Java tutorial, when you join a session, a token is generated like so: ` String token = session.generateToken(tokenOptions);`. The token generated is in this form: 0a4b8d8ikdo53wsl, 73hmvkapoe2ztgtm,...

Then the client code takes that token and connects to the session like so:
`session.connect(token, metadata).then(...).catch(...)`

I got an error with that though: 
![image](https://user-images.githubusercontent.com/39285078/40030406-98296c12-5814-11e8-9d04-33a299a5a008.png)

After some digging around I am led to believe it's because of Session.prototype.processToken, which has this line: `var url = new URL(token)`, which supposedly throws an error because the token received isn't an url?

My Openvidu server has been functioning well before I upgrade my code to 2.0.0. When this error happens, the server does not receive any event.

I think I am most likely missing something, so if you will clarify this for me I'll be most grateful.

**Comment by micaelgallego** [comment]
Is seems you have a version mismatch problem. Are you sure all your pieces
are updated to 2.0.0 version?

**Comment by dustgrinder** [comment]
I believe they are, since the Java client recording-related methods were Recording instead of Archive, the client I got from your repository properly, and the docker image was also updated.

May you tell me what the expected behavior here is? Which piece do you suspect that leads to this mismatch?

**Comment by pabloFuente** [comment]
If your tokens have a format like `0a4b8d8ikdo53wsl`, then your OpenVidu Server is not properly upgraded. If you are running a Docker image, be sure to force the new version with a "docker pull".

**Comment by dustgrinder** [comment]
I updated and it worked properly. I apologize for all the troubles and thank you all for helping!
