### ISSUE TITLE
When I set SessionActivity's ScreenOrientation to landscape, I can't see localVideoView

### ISSUE THREAD

**Issue by mutoude** [OpenVidu/openvidu-tutorials#81]

**Comment by micaelgallego** [comment]
In which tutorial?

**Comment by mutoude** [comment]
Andoid

**Comment by matkey** [comment]
Just wondering if there are any updates? 
It occurs using a fresh download of the openvidu-android example code. 
To trigger the issue, change "setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);" in SessionActivity.java to "setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);"

https://stackoverflow.com/questions/64069183/android-webrtc-surfaceviewrenderer-preview-goes-blank-when-i-start-the-activity seems to suggest its WebRTC related, but as it occurs in the demo code, users will see it here first.

**Comment by matkey** [comment]
FYI If I force the code in createCameraCapturer to use Camera1Enumerator then portrait mode works

**Comment by daniel-reinhold** [comment]
Faced the same issue, any new findings?

**Comment by drunkendaddy** [comment]
facing the same issue. any updates?

**Comment by micaelgallego** [comment]
The OpenVidu Android tutorial is a basic application implemented with demo proposes. 

If you find any issue with it, please contribute the fixes and we will include them in the application.

Best regards

**Comment by anyan131** [comment]
facing the same issue, any progress?

**Comment by 0000005** [comment]
Faced the same issue, any new findings?

**Comment by fuzz1** [comment]
I also encountered the same situation, changing the page to landscape display when the camera picture will not show, my solution is to unify 'EglBaseContext', which is a global context, such changes are effective.

**Comment by liujiujin2006** [comment]
> I also encountered the same situation, changing the page to landscape display when the camera picture will not show, my solution is to unify 'EglBaseContext', which is a global context, such changes are effective.

How to do it?
