### ISSUE TITLE
URL on tutorial is wrong

### ISSUE THREAD

**Issue by meteficha** [OpenVidu/openvidu-tutorials#83]
Hello!  Not sure where the tutorial webpages are being hosted from, but there's a problem with https://openvidu.io/docs/tutorials/openvidu-js-node/.  Where it says:

```
node server.js localhost:4443 MY_SECRET
```

it should read:

```
node server.js https://localhost:4443 MY_SECRET
```

Otherwise an error in a completely different location pops up when trying to create a new session.

**Comment by pabloFuente** [comment]
You are completely right. Issue has been already addressed and documentation is fixed.

Thank you for reporting!
