### ISSUE TITLE
Video Mirror

### ISSUE THREAD

**Issue by jcdmacleod** [OpenVidu/openvidu-tutorials#85]
I see that the video source is mirrored.  We are testing a use case using a device capture which involves text so this is problematic.  Is this a global setting, or what is dictating that the video should be mirrored?

**Comment by pabloFuente** [comment]
Hi,

See https://openvidu.io/api/openvidu-browser/interfaces/publisherproperties.html#mirror

**Comment by jcdmacleod** [comment]
I am a bit confused as the page referenced states that this only impacts the local view of the publisher in the browser, however, it is still mirrored when recorded.  So is this setting correct?

Whether the publisher's video will be mirrored in the page or not. Only affects the local view of the publisher in the browser (remote streams will not be mirrored). If videoSource is set to "screen" this property is fixed to false
