### ISSUE TITLE
set up your room

### ISSUE THREAD

**Issue by andreaBussotti** [OpenVidu/openvidu-tutorials#86]
good evening, i am implementing my application with the openvidu-webcomponent code.
I noticed that it does not correctly manage the page in question in the mobile.
the js file (minified) is not easily legible, nor debuggable.

how can I solve this problem?

good evening

Andrea

**Comment by micaelgallego** [comment]
Please use https://openvidu.discourse.group/ for questions.

To modify OpenVidu Web Component you have to modify [OpenVidu Call project](https://openvidu.io/docs/demos/openvidu-call/) and generate the Web Component from it.
