### ISSUE TITLE
Openvidu ionic ios more than 2 users in the same session

### ISSUE THREAD

**Issue by alexpeke** [OpenVidu/openvidu-tutorials#87]
Hello,
I'm using your openvidu-ionic demo app in ios pointing to my own openvidu server and if I have 3 users connected to the same session, (2 from browser and 1 from ios), one of the streams is shown repeated in the app per each connected user and the other streams don't appear.

Tested in Ipad Mini 2.
IOS version 12.4.5.

Regards

**Comment by micaelgallego** [comment]
Please can you provide an screen shot to understand better the problem you are having? Please can you test other combinations between browsers, android phones and iOS devices to see the behavior in such situations?

**Comment by alexpeke** [comment]
These are the screenshots you requested.
1º Screenshot is from android
2º Screenshot is from ios

![Screenshot_2020-03-30-11-46-53](https://user-images.githubusercontent.com/62706709/77903251-d39fc680-7282-11ea-96ab-16f49d2aa3ee.png)
![IMG_20200330_114711](https://user-images.githubusercontent.com/62706709/77905128-026b6c00-7286-11ea-9780-8f7a8cb3a66c.jpg)
 
Participant3 is the IOS device.
Android is the android device.
The other two connections are mozilla and chrome.

As you can see, IOS shows the same stream repeatedly while android shows it correctly.

I hope hearing from you.

**Comment by CSantosM** [comment]
Hello @alexpeke 

We've tested this demo and you're right.
This issue looks like a cordova-plugin-iosrtc bug. If you can check it, changing the cordova-plugin-iosrtc version to 6.7.0 and rebuild de app, this issue is solved.

We've opened a [issue](https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/480) for this bug.

Regards.

**Comment by alexpeke** [comment]
It works when I update the plugin to 6.0.7 version.

Thank you very much for the support and the fast response.

Regards.
