### ISSUE TITLE
Openvidu ionic ios video freezing error

### ISSUE THREAD

**Issue by alexpeke** [OpenVidu/openvidu-tutorials#88]
Hello,
I'm using your openvidu-ionic demo app in ios pointing to my own openvidu server, if I hide the subscriber control (like this <ion-col size="6" *ngFor="let sub of subscribers" style="display:none;">) and run the app without debugging. The ios video seems like freezes in its own device.

Tested in Ipad Mini 2.
IOS version 12.4.5.
Iosrtc version 6.0.7.

Regards

**Comment by micaelgallego** [comment]
Can you clarify what you mean by "The ios video seems like freezes in its own device." I don't understand the issue.

**Comment by CSantosM** [comment]
Closed issue for inactivity
