### ISSUE TITLE
Unable to find speaking participant event in andorid

### ISSUE THREAD

**Issue by sravan41-elorce** [OpenVidu/openvidu-tutorials#91]
Working with Openvidu, We are unable to find an event which highlights the speaking participant.We would like to get some help regarding this.

Thanks & Regards
Sravan V

**Comment by pabloFuente** [comment]
https://openvidu.discourse.group/t/need-help-getting-equivalent-of-start-stop-speaking-events-on-android/238?u=pablofuente
