### ISSUE TITLE
OpenVidu-Ionic tutorial - Video and Voice streaming not working in iPhone 

### ISSUE THREAD

**Issue by bimal72** [OpenVidu/openvidu-tutorials#92]
Hello,

I have downloaded and run OpenVidu Ionic tutorial on browser and iPhone.
I have two iPhone - iPhone 11 Promx with OS > 13
another iPhone with OS > 12

I have tried with each iphone and web browser but in all cases, I am getting camera on, but not video and voice transfer (streaming).

Please find attached video in zip file.

I have changed 
OPENVIDU_SERVER_URL = 
    OPENVIDU_SERVER_SECRET =
Point to our installed Server.

Do I need to configure something in server? Am I missing something? 

[openvidu_ionic.zip](https://github.com/OpenVidu/openvidu-tutorials/files/4532462/openvidu_ionic.zip)

**Comment by micaelgallego** [comment]
How have you deployed OpenVidu platform.

Can you test with OpenVidu platform deployed on https://demosopenstack.openvidu.io with secret MY_SECRET?

**Comment by bimal72** [comment]
Hello, Sorry for late replying.
I have used  https://demosopenstack.openvidu.io with secret MY_SECRET with your latest openvidu-ionic tutorial (just updated before 2 days)

Unfortunately it is not running in my iPhone Pro Max, giving some certificate error.

I have attached one image and video... please look in this. Am I Missing something?
![openvidu_ionic](https://user-images.githubusercontent.com/923301/80577758-0cb78c00-8a25-11ea-85be-617f6721d730.jpg)
[openvidu_2.zip](https://github.com/OpenVidu/openvidu-tutorials/files/4550626/openvidu_2.zip)

**Comment by OscarSotoSanchez** [comment]
Hi bimal72 , 

Try same but with https://demos.openvidu.io url and MY_SECRET secret.

Regards

**Comment by bimal72** [comment]
@OscarSotoSanchez  yes, this is working very well.

Also our server is working now, out IT Admin forgot to re implement firewall policy.
Thanks for your support

**Comment by pabloFuente** [comment]
Hi,

Please bear in mind that this server is only for testing/demos purposes. You MUST deploy your own OpenVidu server asap to develop and take to production your app. This server is not providing OpenVidu as a service, and is NOT secure (anyone could connect to your sessions or record them).

**Comment by bimal72** [comment]
We have already setup our own and in that server we were facing issue. Since your version upgrade out IT Admin forgot some firewall policy settings, now resolved and working fine. Even we are using our own client UI running in iFrame even in iPhone now
