### ISSUE TITLE
Cannot not get react-native ios app to run.

### ISSUE THREAD

**Issue by ericklind** [OpenVidu/openvidu-tutorials#96]
I've been trying to get the react-native ios app to run, but I've had no luck. When I run the react-native project (pm react-native start or yarn start) I get the react symbol and 
`
To reload the app press "r"
To open developer menu press "d"
`

The problem is nothing actually happens. If I press d, I get an error message that no apps are running. If I try to open it in XCode, I get the following error:

`/Users/erick/Documents/Code/openvidu-tutorials/openvidu-react-native/ios/Pods/Target Support Files/Pods-openvidu_react_native/Pods-openvidu_react_native.debug.xcconfig: unable to open file (in target "openvidu_react_native" in project "openvidu_react_native")
`

How do I fix this?

**Comment by ericklind** [comment]
It looks like I may have needed to run pd install. I did that but now I'm getting this error:
` No podspec found for `react-native-webrtc` in `../node_modules/openvidu-browser/node_modules/react-native-webrtc``

There is no react-native-webrtc in that folder. How do I fix this?

**Comment by CSantosM** [comment]
As the [openvidu-react-native docs](https://docs.openvidu.io/en/2.13.0/tutorials/openvidu-react-native/) says ...
![image](https://user-images.githubusercontent.com/10628395/80458639-63439e00-8931-11ea-9e0e-0fa4b5ab1359.png)

**Comment by CSantosM** [comment]
Closed issue because it's not an issue. For such matters, please use [OpenVidu Forum](https://openvidu.discourse.group/).
