### ISSUE TITLE
Update code to match tutorial

### ISSUE THREAD

**Issue by bensch128** [OpenVidu/openvidu-tutorials#97]
Please  update
https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-webcomponent/web/app.js
to match
https://docs.openvidu.io/en/2.13.0/tutorials/openvidu-webcomponent/#appjs-i-openvidu-web-component-events

Thanks!
Ben

**Comment by CSantosM** [comment]
This will be ready in the next OpenVidu release
