### ISSUE TITLE
https://localhost:4443 error using my own certificates

### ISSUE THREAD

**Issue by sernocturno** [OpenVidu/openvidu-tutorials#98]
hello everyone.
i have a server running all ok, but when i use my own certificates the as say here [https://docs.openvidu.io/en/2.12.0/deployment/deploying-ubuntu/#using-your-own-certificate](url)
when i run the server with this command
`java -jar -Dopenvidu.secret=MY_SECRET -Dserver.ssl.key-store=/opt/openvidu/my_keystore.jks -Dserver.ssl.key-store-password=MY_KEYSTORE_SECRET -Dserver.ssl.key-alias=my_cert_alias openvidu-server-2.5.0.jar`
the websocket connection is pointing to wss://localhost:4443/openvidu instead wss://<my_url>:4443/openvidu.

i try to adding  `-Dopenvidu.publicurl=https://<my_url>:4443`  to the java command, but when i run the testing, the browser cert is not my cert, is the openvidu cert

hope somebody help me with this

p/d: English is not my mother language

**Comment by micaelgallego** [comment]
I recommend you to deploy the latest OpenVidu version (2.13 at the time of writing) as it allows you to change cert very easily

**Comment by diegolopez15** [comment]
buenas tardes como puedo  ejecutar localhost:4443
