### ISSUE TITLE
Android remove stream from remote connection

### ISSUE THREAD

**Issue by rfazi** [OpenVidu/openvidu-tutorials#99]
**Describe the bug**
The remote connection will not return the stream if I do not load my stream even if I add the constant **offerToReceiveAudio** and **offerToReceiveVideo**.

**Expected behavior**
When I create remote connections I expect to receive the remote stream including audio and video even if I don't upload my audio and video including the **offerToReceiveAudio** and **offerToReceiveVideo** constants.

**Wrong current behavior**
If I do not add my streams to the remote connection, the connection does not return the remote streams.

**OpenVidu tutorial where to replicate the error**
Tutorial for Android: 
**Session.java** -> public void **createRemotePeerConnection**
Comment out `peerConnection.addStream` or `mediaStream.addTrack`.
**CustomWebSocket.java** -> private void **subscribeAux**
Add
```javascript
MediaConstraints sdpConstraints = new MediaConstraints();
sdpConstraints.mandatory.add(new MediaConstraints.KeyValuePair("offerToReceiveAudio", "true"));
sdpConstraints.mandatory.add(new MediaConstraints.KeyValuePair("offerToReceiveVideo", "true"));
```
and replace `new MediaConstraints()` for '**createOffer**' method with `sdpConstraints`.

**OpenVidu deployment info**
- Docker container as explained in OpenVidu tutorials, with './openvidu start' command on Debian 10.3.

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Android 9
- Chrome 81

**Comment by micaelgallego** [comment]
I've moved the issue because is a problem in a tutorial

**Comment by rfazi** [comment]
OK, in the meantime I have fixed the issue.
I will create a pull request when I have time.
Thanks anyway.

**Comment by micaelgallego** [comment]
Cool!

**Comment by rfazi** [comment]
I've created a PR #100

**Comment by micaelgallego** [comment]
Thank you. We will take a look in the following days.
